import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { PrismaClient, type Role } from "@prisma/client";
import bcrypt from "bcryptjs";

type Day1Role = "STUDENT" | "TEACHER" | "GUARDIAN" | "ADMIN" | "MOE";

type RoleConfig = {
  label: Day1Role;
  dbRole: Role;
  emailEnv: string;
  passwordEnv: string;
  passwordSources: string[];
};

const envPath = path.join(process.cwd(), ".env.local");
const outputPath = path.join(process.cwd(), ".env.e2e.local");

const roles: RoleConfig[] = [
  {
    label: "STUDENT",
    dbRole: "STUDENT",
    emailEnv: "E2E_DEMO_STUDENT_EMAIL",
    passwordEnv: "E2E_DEMO_STUDENT_PASSWORD",
    passwordSources: ["E2E_DEMO_STUDENT_PASSWORD", "DEMO_SEED_PASSWORD"],
  },
  {
    label: "TEACHER",
    dbRole: "TEACHER",
    emailEnv: "E2E_DEMO_TEACHER_EMAIL",
    passwordEnv: "E2E_DEMO_TEACHER_PASSWORD",
    passwordSources: ["E2E_DEMO_TEACHER_PASSWORD", "DEMO_SEED_PASSWORD"],
  },
  {
    label: "GUARDIAN",
    dbRole: "GUARDIAN",
    emailEnv: "E2E_DEMO_GUARDIAN_EMAIL",
    passwordEnv: "E2E_DEMO_GUARDIAN_PASSWORD",
    passwordSources: ["E2E_DEMO_GUARDIAN_PASSWORD", "DEMO_SEED_PASSWORD"],
  },
  {
    label: "ADMIN",
    dbRole: "ADMIN",
    emailEnv: "E2E_DEMO_ADMIN_EMAIL",
    passwordEnv: "E2E_DEMO_ADMIN_PASSWORD",
    passwordSources: ["E2E_DEMO_ADMIN_PASSWORD", "DEMO_SEED_PASSWORD"],
  },
  {
    label: "MOE",
    dbRole: "MOE_OFFICIAL",
    emailEnv: "E2E_DEMO_MOE_EMAIL",
    passwordEnv: "E2E_DEMO_MOE_PASSWORD",
    passwordSources: ["E2E_DEMO_MOE_PASSWORD", "DEMO_MOE_PASSWORD", "DEMO_SEED_PASSWORD"],
  },
];

function loadEnvLocal() {
  if (!existsSync(envPath)) return;

  for (const line of readFileSync(envPath, "utf8").split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;

    const separator = trimmed.indexOf("=");
    if (separator <= 0) continue;

    const key = trimmed.slice(0, separator).trim();
    const value = unquoteEnvValue(trimmed.slice(separator + 1).trim());
    process.env[key] = value;
  }
}

function unquoteEnvValue(value: string) {
  let current = value.trim();
  let changed = true;
  while (changed) {
    changed = false;
    if (current.endsWith("\\n")) {
      current = current.slice(0, -2).trimEnd();
      changed = true;
    }
    if (current.startsWith('"') || current.startsWith("'")) {
      current = current.slice(1);
      changed = true;
    }
    if (current.endsWith('"') || current.endsWith("'")) {
      current = current.slice(0, -1);
      changed = true;
    }
  }
  return current;
}

function readRequiredPassword(config: RoleConfig) {
  for (const key of config.passwordSources) {
    const value = process.env[key]?.trim();
    if (value) return value;
  }

  throw new Error(
    `${config.label} password is missing. Set DEMO_SEED_PASSWORD or role-specific E2E password env locally.`,
  );
}

function escapeEnvValue(value: string) {
  return JSON.stringify(value);
}

function normalizeDatabaseUrlForScript() {
  const databaseUrl = process.env.DATABASE_URL?.trim();
  if (!databaseUrl?.match(/^postgres(ql)?:\/\//)) return;

  const url = new URL(databaseUrl);
  for (const key of ["pgbouncer", "connection_limit"]) {
    url.searchParams.delete(key);
  }
  process.env.DATABASE_URL = url.toString();
}

async function main() {
  loadEnvLocal();
  normalizeDatabaseUrlForScript();

  const prisma = new PrismaClient();
  try {
    const output: Record<string, string> = {};

    for (const config of roles) {
      const user = await prisma.user.findFirst({
        where: {
          role: config.dbRole,
          email: { not: "" },
          hashedPwd: { not: null },
        },
        orderBy: { createdAt: "asc" },
        select: { id: true, email: true },
      });

      if (!user?.email) {
        throw new Error(`No existing seeded demo user found for role ${config.label}.`);
      }

      output[config.emailEnv] = user.email;
      output[config.passwordEnv] = readRequiredPassword(config);

      await prisma.user.update({
        where: { id: user.id },
        data: {
          hashedPwd: await bcrypt.hash(output[config.passwordEnv], 10),
          passwordChangedAt: new Date(),
        },
      });
    }

    mkdirSync(path.dirname(outputPath), { recursive: true });
    writeFileSync(
      outputPath,
      [
        "# Generated by npm run e2e:prepare-day1.",
        "# Local E2E credentials only. Do not commit this file.",
        ...roles.flatMap((config) => [
          `${config.emailEnv}=${escapeEnvValue(output[config.emailEnv])}`,
          `${config.passwordEnv}=${escapeEnvValue(output[config.passwordEnv])}`,
        ]),
        "",
      ].join("\n"),
      { encoding: "utf8", mode: 0o600 },
    );

    console.log(`Prepared ${roles.length} Day 1 E2E role credential pairs in .env.e2e.local.`);
    console.log(`Reset ${roles.length} demo user password hashes.`);
    console.log("Credential values were not printed.");
  } finally {
    await prisma.$disconnect();
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
