import QRCode from "qrcode";

export type SubjectBreakdown = {
  subject: string;
  assignmentsCompleted: number;
  avgScore: number;
  bestScore: number;
};

export type PortfolioPdfData = {
  studentName: string;
  schoolName: string;
  grade: string;
  academicYear: string;
  term: string;
  avgScore: number;
  attendance: number;
  lessonsComplete: number;
  verifyToken: string;
  generatedAt: Date;
  subjects: SubjectBreakdown[];
};

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function pct(n: number): string {
  return `${Math.round(n)}%`;
}

export async function generatePortfolioHtml(data: PortfolioPdfData): Promise<string> {
  const baseUrl =
    process.env.NEXT_PUBLIC_APP_URL ??
    process.env.VERCEL_URL
      ? `https://${process.env.VERCEL_URL}`
      : "https://liberia-learn.vercel.app";

  const verifyUrl = `${baseUrl}/credential/${data.verifyToken}`;
  const qrDataUrl = await QRCode.toDataURL(verifyUrl, { width: 120, margin: 1 });

  const subjectRows = data.subjects
    .map(
      (s) => `
    <tr>
      <td>${esc(s.subject)}</td>
      <td>${s.assignmentsCompleted}</td>
      <td>${pct(s.avgScore)}</td>
      <td>${pct(s.bestScore)}</td>
    </tr>`,
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<style>
  body { font-family: Arial, sans-serif; color: #1a1a1a; margin: 40px; font-size: 13px; }
  h1 { font-size: 22px; margin-bottom: 4px; }
  h2 { font-size: 16px; margin-top: 32px; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; }
  .badge { background: #f59e0b; color: #fff; padding: 2px 10px; border-radius: 12px; font-size: 11px; font-weight: bold; }
  .meta { color: #555; font-size: 12px; }
  .stats { display: flex; gap: 40px; margin: 20px 0; }
  .stat-box { border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px 20px; text-align: center; }
  .stat-val { font-size: 24px; font-weight: bold; color: #1a1a1a; }
  .stat-lbl { font-size: 11px; color: #777; }
  table { width: 100%; border-collapse: collapse; margin-top: 12px; }
  th { background: #f9fafb; font-size: 12px; font-weight: 600; text-align: left; padding: 8px; border: 1px solid #e5e7eb; }
  td { padding: 8px; border: 1px solid #e5e7eb; font-size: 12px; }
  .qr-section { margin-top: 28px; display: flex; align-items: flex-start; gap: 20px; }
  .qr-caption { font-size: 11px; color: #555; max-width: 260px; }
  .footer { margin-top: 40px; font-size: 11px; color: #888; border-top: 1px solid #e5e7eb; padding-top: 12px; }
  .verify-url { font-family: monospace; font-size: 11px; color: #d97706; word-break: break-all; }
</style>
</head>
<body>
<div class="header">
  <div>
    <p class="badge">LiberiaLearn — Official Transcript</p>
    <h1>${esc(data.studentName)}</h1>
    <p class="meta">${esc(data.schoolName)} · ${esc(data.grade)} · ${esc(data.academicYear)}</p>
    <p class="meta">Term: ${esc(data.term)} · Generated: ${data.generatedAt.toLocaleDateString()}</p>
  </div>
  <div style="text-align:right; font-size:11px; color:#888;">
    <div style="font-weight:bold; color:#1a1a1a;">Ministry of Education</div>
    <div>Republic of Liberia</div>
  </div>
</div>

<div class="stats">
  <div class="stat-box">
    <div class="stat-val">${pct(data.avgScore)}</div>
    <div class="stat-lbl">Average Grade</div>
  </div>
  <div class="stat-box">
    <div class="stat-val">${pct(data.attendance)}</div>
    <div class="stat-lbl">Attendance</div>
  </div>
  <div class="stat-box">
    <div class="stat-val">${data.lessonsComplete}</div>
    <div class="stat-lbl">Lessons Completed</div>
  </div>
</div>

<h2>Subject Breakdown</h2>
<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Assignments Completed</th>
      <th>Avg Score</th>
      <th>Best Score</th>
    </tr>
  </thead>
  <tbody>
    ${subjectRows || '<tr><td colspan="4" style="color:#888;">No subject data for this term.</td></tr>'}
  </tbody>
</table>

<div class="qr-section">
  <img src="${qrDataUrl}" width="120" height="120" alt="QR Code"/>
  <div class="qr-caption">
    <strong>Verify this transcript</strong><br/>
    Scan the QR code or visit:<br/>
    <span class="verify-url">${verifyUrl}</span><br/><br/>
    This document can be verified at the URL above. Anyone with a smartphone can confirm its authenticity instantly.
  </div>
</div>

<div class="footer">
  Generated by LiberiaLearn on behalf of the Liberia Ministry of Education.<br/>
  This is an official learning record. Verification available online for 1 year from date of generation.
</div>
</body>
</html>`;
}
