/**
 * Product Redesign V1 / Learner Experience V2 — Lesson Player V2 scene contract.
 *
 * A LessonExperience is authored (or generated by Curriculum V2) as an ordered
 * list of instructional scenes. Scenes are the long-term authority for lesson
 * structure; `parseToSlides` is only a compatibility fallback for legacy bodies.
 * See docs/architecture/LEARNER_EXPERIENCE_V2.md.
 *
 * Nothing in this contract scores, grades or writes mastery. Scenes declare the
 * evidence they may emit; the existing Evidence → SLM → DecisionModel →
 * Learning Orchestrator chain stays the only learning authority.
 */
import type { GovernedEvidenceType } from "@/lib/learning-evidence/evidenceContract";

export const LESSON_EXPERIENCE_CONTRACT_VERSION = "lesson-experience/1.0.0" as const;

export const SCENE_TYPES = [
  "INTRO", "OBJECTIVE", "EXPLANATION", "MEDIA", "INTERACTIVE_DIAGRAM", "GUIDED_EXAMPLE",
  "PRACTICE", "CHECK_UNDERSTANDING", "LAB", "REFLECTION", "REVIEW", "MASTERY_CHECK",
] as const;
export type SceneType = (typeof SCENE_TYPES)[number];

/** Presentation bands for the same scene contract. The learning objective never changes by band. */
export type AgeBand = "EARLY_PRIMARY" | "UPPER_PRIMARY" | "JUNIOR_SECONDARY" | "SENIOR_SECONDARY";

/**
 * Where a lesson experience's authority comes from. Only APPROVED_RELEASE content
 * may be shown to real students; PROTOTYPE_FIXTURE is internal-only.
 */
export type ContentAuthorityStatus = "APPROVED_RELEASE" | "CURRICULUM_V2_DRAFT" | "PROTOTYPE_FIXTURE" | "LEGACY_UNGOVERNED";

export type ExperienceObjective = Readonly<{
  id: string;
  statement: string;
  conceptId: string;
  /** Governed references when available (standard → skill → concept). Empty means not yet curriculum-bound. */
  standardCodes: readonly string[];
  skillIds: readonly string[];
}>;

export type SceneContent = Readonly<{
  /** Instructional text in the lesson markdown subset (rendered through the existing sanitising renderer). */
  body: string;
  keyPoints?: readonly string[];
  /** Optional per-band wording. Missing bands fall back to `body`. */
  ageVariants?: Partial<Record<AgeBand, Readonly<{ body: string; keyPoints?: readonly string[] }>>>;
}>;

export type SceneMedia = Readonly<{
  kind: "IMAGE" | "DIAGRAM" | "VIDEO" | "AUDIO";
  ref: string;
  /** Required text alternative; media without one is rejected by validation. */
  alt: string;
  transcript?: string;
  captionsRef?: string;
  offlineBytes?: number;
}>;

export type FormativeItem = Readonly<{
  id: string;
  prompt: string;
  options: readonly string[];
  /**
   * Formative checks only: the key ships to the client so feedback is instant
   * and offline. Formative results are observations, never scored evidence.
   */
  correctIndex: number;
  feedback: Readonly<{ correct: string; incorrect: string }>;
  /** Optional feedback per option (same order as options), so each distractor answers its own misconception. */
  optionFeedback?: readonly string[];
}>;

export type DiagramStep = Readonly<{ id: string; label: string; description: string }>;

export type AssessmentItemRef = Readonly<{ itemId: string; itemVersion: string; prompt: string; options: readonly string[] }>;

/**
 * The integration seam for Assessment Player V2. A lesson hands off to an
 * assessment experience by reference; it never embeds an answer key for
 * mastery items. Phase A renders a bounded response collector; scoring belongs
 * to the server-side assessment authority.
 */
export type AssessmentHandoff = Readonly<{
  assessmentId: string;
  assessmentVersion: string;
  player: "ASSESSMENT_PLAYER_V2";
  objectiveIds: readonly string[];
  items: readonly AssessmentItemRef[];
  scoring: "SERVER_AUTHORITY";
}>;

export type SceneInteraction =
  | Readonly<{ kind: "NONE" }>
  | Readonly<{ kind: "DIAGRAM_REVEAL"; diagramId: string; steps: readonly DiagramStep[] }>
  | Readonly<{ kind: "MULTIPLE_CHOICE"; items: readonly FormativeItem[] }>
  | Readonly<{ kind: "FREE_RESPONSE"; prompts: readonly Readonly<{ id: string; prompt: string; minLength: number }>[] }>
  | Readonly<{ kind: "LAB_LAUNCH"; linkId: string }>
  | Readonly<{ kind: "ASSESSMENT_HANDOFF"; assessment: AssessmentHandoff }>;

/** Ids from the existing classroom toolkit registry (lib/toolkit/toolRegistry.ts). */
export type SceneToolPermissions = Readonly<{ allowed: readonly string[]; prohibited: readonly string[] }>;

export type SceneAccessibility = Readonly<{
  /** Text that conveys the scene's learning content without visuals, motion or 3D. */
  textAlternative: string;
  keyboardOperable: boolean;
  reducedMotionSafe: boolean;
  captionsRequired: boolean;
}>;

export type SceneOffline = Readonly<{
  /** FULL: works from the cached lesson. DEGRADED: works with the stated fallback. ONLINE_ONLY: blocked offline. */
  mode: "FULL" | "DEGRADED" | "ONLINE_ONLY";
  fallback: string;
}>;

export type SceneEvidenceContract =
  | Readonly<{ kind: "NONE" }>
  | Readonly<{ kind: "FORMATIVE_OBSERVATION" | "LAB_OBSERVATION" | "REFLECTION" | "MASTERY_RESPONSE"; evidenceType: GovernedEvidenceType; objectiveIds: readonly string[] }>;

export type SceneCompletionRule =
  | Readonly<{ kind: "VIEWED" }>
  | Readonly<{ kind: "ALL_STEPS_REVEALED" }>
  | Readonly<{ kind: "ALL_ANSWERED" }>
  | Readonly<{ kind: "LAB_RETURNED_OR_FALLBACK" }>
  | Readonly<{ kind: "ALL_RESPONSES_WRITTEN" }>;

export type Scene = Readonly<{
  id: string;
  type: SceneType;
  title: string;
  objectiveIds: readonly string[];
  content: SceneContent;
  interaction: SceneInteraction;
  media?: readonly SceneMedia[];
  tools: SceneToolPermissions;
  accessibility: SceneAccessibility;
  offline: SceneOffline;
  evidence: SceneEvidenceContract;
  completion: SceneCompletionRule;
}>;

export type LessonExperience = Readonly<{
  contractVersion: typeof LESSON_EXPERIENCE_CONTRACT_VERSION;
  id: string;
  version: string;
  title: string;
  subject: string;
  grade: number;
  ageBand: AgeBand;
  authority: Readonly<{
    status: ContentAuthorityStatus;
    note: string;
    /** Repository content that might later carry this lesson. Listing one is not approval. */
    candidateContentIds: readonly string[];
    releaseId: string | null;
    /** Deterministic identity of the pinned ontology release (never the lesson version). */
    releaseIdentity?: string | null;
  }>;
  objectives: readonly ExperienceObjective[];
  scenes: readonly Scene[];
  offline: Readonly<{ packageable: boolean; requiredAssets: readonly string[] }>;
}>;

/** Where the scenes being played came from (the slide/scene migration hierarchy). */
export type SceneSource = "NATIVE_SCENES" | "GOVERNED_SECTIONS" | "PARSED_SLIDES_FALLBACK" | "LEGACY_READ_MODE";
