import type { CapabilityProfile } from "../../types";
import type { GeometryMesh, InstructionalGeometryVariants, ParametricDescriptor, ProfileGeometry } from "./types";

const finite = (n: number) => Number.isFinite(n);
const assert: (ok: unknown, message: string) => asserts ok = (ok, message) => { if (!ok) throw new Error(`invalid_parametric_geometry:${message}`); };
function intersects(a:readonly number[],b:readonly number[],c:readonly number[],d:readonly number[]){const cross=(p:readonly number[],q:readonly number[],r:readonly number[]) =>(q[0]-p[0])*(r[1]-p[1])-(q[1]-p[1])*(r[0]-p[0]);return cross(a,b,c)*cross(a,b,d)<0&&cross(c,d,a)*cross(c,d,b)<0;}
function mesh(positions: number[], indices: number[]): GeometryMesh {
  assert(positions.length % 3 === 0 && indices.length % 3 === 0, "triangle_data");
  assert(positions.every(finite), "non_finite_vertex");
  const normals = new Float32Array(positions.length);
  for (let i = 0; i < indices.length; i += 3) {
    const a = indices[i] * 3, b = indices[i + 1] * 3, c = indices[i + 2] * 3;
    const ux = positions[b] - positions[a], uy = positions[b + 1] - positions[a + 1], uz = positions[b + 2] - positions[a + 2];
    const vx = positions[c] - positions[a], vy = positions[c + 1] - positions[a + 1], vz = positions[c + 2] - positions[a + 2];
    const nx = uy * vz - uz * vy, ny = uz * vx - ux * vz, nz = ux * vy - uy * vx;
    for (const j of [a, b, c]) { normals[j] += nx; normals[j + 1] += ny; normals[j + 2] += nz; }
  }
  for (let i = 0; i < normals.length; i += 3) { const d = Math.hypot(normals[i], normals[i + 1], normals[i + 2]) || 1; normals[i] /= d; normals[i + 1] /= d; normals[i + 2] /= d; }
  const vertexCount = positions.length / 3;
  assert(vertexCount <= 65535, "vertex_limit");
  return { positions: new Float32Array(positions), normals, indices: new Uint16Array(indices), triangles: indices.length / 3 };
}
const quality = (profile: CapabilityProfile, high: number, standard: number, low: number) => profile === "HIGH" ? high : profile === "STANDARD" ? standard : low;
function lathe(d: Extract<ParametricDescriptor, {kind:"lathe"}>, p: CapabilityProfile): GeometryMesh {
  assert(d.profile.length >= 2 && d.profile.every(([r,y]) => finite(r) && finite(y) && r >= 0 && Math.abs(r) <= 1000 && Math.abs(y) <= 1000) && d.profile.some((point,index)=>index>0&&(point[0]!==d.profile[0][0]||point[1]!==d.profile[0][1])), "lathe_profile");
  const requested = d.radialSegments ?? quality(p,48,32,12), radial = Math.min(requested, quality(p,48,32,12)); assert(Number.isInteger(requested) && requested >= 3 && radial <= 128, "lathe_segments");
  const positions: number[] = [], indices: number[] = [];
  for (const [r,y] of d.profile) for (let j=0;j<radial;j++){const a=2*Math.PI*j/radial;positions.push(r*Math.cos(a),y,r*Math.sin(a));}
  for(let i=0;i<d.profile.length-1;i++)for(let j=0;j<radial;j++){const a=i*radial+j,b=i*radial+(j+1)%radial,c=b+radial,e=a+radial;indices.push(a,c,b,a,e,c);}
  return mesh(positions,indices);
}
function sweep(d: Extract<ParametricDescriptor,{kind:"sweep"}>, p: CapabilityProfile): GeometryMesh {
  assert(d.points.length>=(d.closed?3:2)&&d.points.length<=4096&&d.points.every(v=>v.length===3&&v.every(value=>finite(value)&&Math.abs(value)<=1000)) && finite(d.radius)&&d.radius>0&&d.radius<=1000,"sweep_path");
  const requested=d.radialSegments??quality(p,16,10,6),n=Math.min(requested,quality(p,16,10,6));assert(Number.isInteger(requested)&&requested>=3&&n<=64,"sweep_segments");
  const positions:number[]=[],indices:number[]=[];
  for(let i=0;i<d.points.length;i++) { const q=d.points[i],prev=d.points[d.closed?(i+d.points.length-1)%d.points.length:Math.max(i-1,0)],next=d.points[d.closed?(i+1)%d.points.length:Math.min(i+1,d.points.length-1)]; let tx=next[0]-prev[0],ty=next[1]-prev[1],tz=next[2]-prev[2],len=Math.hypot(tx,ty,tz); assert(len>1e-8,"duplicate_sweep_points");tx/=len;ty/=len;tz/=len; let ux=-ty,uy=tx,uz=0;len=Math.hypot(ux,uy,uz);if(len<1e-6){ux=1;uy=0;uz=0;len=1;}ux/=len;uy/=len;uz/=len;const vx=ty*uz-tz*uy,vy=tz*ux-tx*uz,vz=tx*uy-ty*ux;for(let j=0;j<n;j++){const a=2*Math.PI*j/n;positions.push(q[0]+d.radius*(ux*Math.cos(a)+vx*Math.sin(a)),q[1]+d.radius*(uy*Math.cos(a)+vy*Math.sin(a)),q[2]+d.radius*(uz*Math.cos(a)+vz*Math.sin(a)));}}
  const segments=d.closed?d.points.length:d.points.length-1;for(let i=0;i<segments;i++)for(let j=0;j<n;j++){const a=i*n+j,b=i*n+(j+1)%n,c=(b+n)%(d.points.length*n),e=(a+n)%(d.points.length*n);indices.push(a,b,c,a,c,e);}return mesh(positions,indices);
}
function extrude(d:Extract<ParametricDescriptor,{kind:"extrude"}>):GeometryMesh {
  assert(d.contour.length>=3&&finite(d.depth)&&d.depth>0&&d.depth<=1000&&d.contour.every(p=>p.length===2&&p.every(value=>finite(value)&&Math.abs(value)<=1000)),"extrude_contour");
  const contour=[...d.contour];for(let i=0;i<contour.length;i++){const next=(i+1)%contour.length;assert(Math.hypot(contour[i][0]-contour[next][0],contour[i][1]-contour[next][1])>1e-8,"degenerate_contour_edge");for(let j=i+1;j<contour.length;j++){const jn=(j+1)%contour.length;if(i===j||next===j||jn===i)continue;assert(!intersects(contour[i],contour[next],contour[j],contour[jn]),"self_intersecting_contour");}}let area=0;for(let i=0;i<contour.length;i++){const a=contour[i],b=contour[(i+1)%contour.length];area+=a[0]*b[1]-b[0]*a[1];}assert(Math.abs(area)>1e-8,"degenerate_contour");if(area<0)contour.reverse();
  const positions:number[]=[],indices:number[]=[],n=contour.length;for(const z of [-d.depth/2,d.depth/2])for(const [x,y] of contour)positions.push(x,y,z);
  // Deterministic ear clipping; rejects concave inputs that cannot be triangulated safely.
  const ring=Array.from({length:n},(_,i)=>i),inside=(p:readonly number[],a:readonly number[],b:readonly number[],c:readonly number[])=>{const cross=(u:readonly number[],v:readonly number[],w:readonly number[]) =>(v[0]-u[0])*(w[1]-u[1])-(v[1]-u[1])*(w[0]-u[0]);return cross(a,b,p)>=0&&cross(b,c,p)>=0&&cross(c,a,p)>=0;};const faces:number[][]=[];let guard=n*n;while(ring.length>3&&guard--){let found=false;for(let i=0;i<ring.length;i++){const a=ring[(i+ring.length-1)%ring.length],b=ring[i],c=ring[(i+1)%ring.length],cross=(contour[b][0]-contour[a][0])*(contour[c][1]-contour[b][1])-(contour[b][1]-contour[a][1])*(contour[c][0]-contour[b][0]);if(cross<=1e-10||ring.some(k=>k!==a&&k!==b&&k!==c&&inside(contour[k],contour[a],contour[b],contour[c])))continue;faces.push([a,b,c]);ring.splice(i,1);found=true;break;}if(!found)break;}assert(ring.length===3,"self_intersecting_contour");faces.push(ring);for(const [a,b,c] of faces){indices.push(a,c,b,a+n,b+n,c+n);}for(let i=0;i<n;i++){const j=(i+1)%n;indices.push(i,j,j+n,i,j+n,i+n);}return mesh(positions,indices);
}
function heightfield(d:Extract<ParametricDescriptor,{kind:"heightfield"}>,p:CapabilityProfile):GeometryMesh {
  const maxRows=quality(p,64,48,16),maxCols=quality(p,128,96,32);assert(Number.isInteger(d.rows)&&Number.isInteger(d.columns)&&d.rows>=2&&d.columns>=2&&d.rows<=maxRows&&d.columns<=maxCols,"heightfield_dimensions");assert(d.heights.length===d.rows*d.columns&&d.heights.every(finite)&&d.size.length===2&&d.size.every(v=>finite(v)&&v>0&&v<=10000),"heightfield_data");assert(d.heights.every(height=>Math.abs(height)<=1000),"heightfield_height_bounds");const positions:number[]=[],indices:number[]=[];for(let r=0;r<d.rows;r++)for(let c=0;c<d.columns;c++)positions.push((c/(d.columns-1)-.5)*d.size[0],d.heights[r*d.columns+c],(r/(d.rows-1)-.5)*d.size[1]);for(let r=0;r<d.rows-1;r++)for(let c=0;c<d.columns-1;c++){const a=r*d.columns+c,b=a+1,e=a+d.columns,f=e+1;indices.push(a,e,b,b,e,f);}return mesh(positions,indices);
}
function dimensionLine(d:Extract<ParametricDescriptor,{kind:"dimensionLine"}>):GeometryMesh { const dx=d.end[0]-d.start[0],dy=d.end[1]-d.start[1],dz=d.end[2]-d.start[2],length=Math.hypot(dx,dy,dz);assert(length>1e-8&&[...d.start,...d.end].every(finite),"dimension_line_endpoints");const ticks=d.ticks??0;assert(Number.isInteger(ticks)&&ticks>=0&&ticks<=12,"dimension_line_ticks");const ux=dx/length,uy=dy/length,uz=dz/length;let nx=-uy,ny=ux,nz=0,norm=Math.hypot(nx,ny,nz);if(norm<1e-6){nx=1;ny=0;nz=0;norm=1;}nx/=norm;ny/=norm;nz/=norm;const positions:number[]=[],indices:number[]=[];const addBar=(a:number[],b:number[],half:number)=>{const base=positions.length/3;positions.push(a[0]+nx*half,a[1]+ny*half,a[2]+nz*half,a[0]-nx*half,a[1]-ny*half,a[2]-nz*half,b[0]-nx*half,b[1]-ny*half,b[2]-nz*half,b[0]+nx*half,b[1]+ny*half,b[2]+nz*half);indices.push(base,base+1,base+2,base,base+2,base+3);};addBar([...d.start],[...d.end],0.008);for(let i=0;i<ticks;i++){const t=(i+1)/(ticks+1),center=[d.start[0]+dx*t,d.start[1]+dy*t,d.start[2]+dz*t];addBar([center[0]-nx*.08,center[1]-ny*.08,center[2]-nz*.08],[center[0]+nx*.08,center[1]+ny*.08,center[2]+nz*.08],0.008);}return mesh(positions,indices); }
function build(d:ParametricDescriptor,p:CapabilityProfile):GeometryMesh { switch(d.kind){case"lathe":return lathe(d,p);case"sweep":return sweep(d,p);case"extrude":return extrude(d);case"heightfield":return heightfield(d,p);case"scatter":{assert(Number.isInteger(d.seed)&&d.seed>=-2147483648&&d.seed<=2147483647&&d.transforms.length>0&&d.transforms.length<=10000,"scatter_bounds");const base=build(d.prototype,p),vertexCount=base.positions.length/3;assert(vertexCount*d.transforms.length<=65535,"scatter_vertex_bounds");const positions:number[]=[],indices:number[]=[];for(let i=0;i<d.transforms.length;i++){const t=d.transforms[i];assert([...t.position,...t.rotation,...t.scale].every(v=>finite(v)&&Math.abs(v)<=1000),"scatter_transform");const offset=i*vertexCount;for(let k=0;k<base.positions.length;k+=3){let x=base.positions[k]*t.scale[0],y=base.positions[k+1]*t.scale[1],z=base.positions[k+2]*t.scale[2];const [rx,ry,rz]=t.rotation;[y,z]=[y*Math.cos(rx)-z*Math.sin(rx),y*Math.sin(rx)+z*Math.cos(rx)];[x,z]=[x*Math.cos(ry)+z*Math.sin(ry),-x*Math.sin(ry)+z*Math.cos(ry)];[x,y]=[x*Math.cos(rz)-y*Math.sin(rz),x*Math.sin(rz)+y*Math.cos(rz)];positions.push(x+t.position[0],y+t.position[1],z+t.position[2]);}for(const index of base.indices)indices.push(offset+index);}return mesh(positions,indices);}case"dimensionLine":return dimensionLine(d);} }
export function buildParametricGeometry(descriptor:ParametricDescriptor,profile:Exclude<CapabilityProfile,"FALLBACK_2D">):GeometryMesh { const result=build(descriptor,profile);assert(result.triangles<=20000,"triangle_limit");return result; }
export function parametricTriangleCount(descriptor:ParametricDescriptor,profile:Exclude<CapabilityProfile,"FALLBACK_2D">):number{return buildParametricGeometry(descriptor,profile).triangles;}
export function resolveGeometryVariant(variants:InstructionalGeometryVariants,profile:CapabilityProfile):{descriptor?:ParametricDescriptor;silhouette:InstructionalGeometryVariants["FALLBACK_2D"]}{assert(variants?.HIGH&&variants.STANDARD&&variants.LOW&&variants.FALLBACK_2D?.kind==="polygon"&&variants.FALLBACK_2D.points.length>=3&&variants.FALLBACK_2D.points.every(point=>point.length===2&&point.every(value=>finite(value)&&Math.abs(value)<=1000)),"missing_profile_fallback");if(profile==="FALLBACK_2D")return{silhouette:variants.FALLBACK_2D};const selected=variants[profile];if("kind"in selected&&selected.kind==="sameAs"){assert(profile!=="LOW","low_profile_must_be_explicit");const ref=(variants as unknown as Record<string,ProfileGeometry>)[selected.profile];assert(ref&&"kind"in ref&&ref.kind!=="sameAs","invalid_same_as");return{descriptor:ref as ParametricDescriptor,silhouette:variants.FALLBACK_2D};}return{descriptor:selected as ParametricDescriptor,silhouette:variants.FALLBACK_2D}; }
