"use client";

import * as THREE from "three";
import { useEffect, useRef, type PointerEvent as ReactPointerEvent } from "react";
import type { CapabilityProfile, InteractiveLabDefinition, LabAction, LabState } from "@/lib/interactive-labs/v2/types";
import { buildRenderList, type RenderItem, type RenderList } from "@/lib/interactive-labs/v2/fidelity/renderList";
import { constrainCamera, type CameraPose } from "@/lib/interactive-labs/v2/fidelity/presentation";
import { pickNearest, type ScenePick } from "./picking";
import { useDisplayFidelity } from "./useDisplayFidelity";
import { useSceneActive } from "./useSceneActive";
import { recordFrameSample, shouldDowngrade } from "@/lib/interactive-labs/v2/fidelity/profiles";
import { downgradeFrameBudgetMs } from "@/lib/interactive-labs/v2/production/budgets";
import { fitHorizontalFieldOfView, transformPoint } from "@/lib/interactive-labs/v2/fidelity/math";
import { applyEnvironmentRig, type EnvironmentRig } from "./threeEnvironment";
import { createThreeSceneStores, disposeThreeSceneStores, shadowCasterHash, syncThreeScene, type ThreeSceneStores } from "./threeSceneSync";
import { planThreeFrame, type FramePlan } from "@/lib/interactive-labs/v2/fidelity/framePlan";
import { publishFramePlan, type ReviewFrameProbe } from "@/lib/interactive-labs/v2/review/framePlanEvidence";
import { placeSceneLabels } from "@/lib/interactive-labs/v2/fidelity/labelLayout";

/** Matches the max-[500px] breakpoint that hides secondary (mobileLabel: false) callouts. */
const narrowViewport = () => typeof window !== "undefined" && window.innerWidth <= 500;

/** A11: at most this many part labels in the scene outside guided focus; the parts list carries the rest. */
const SCENE_LABEL_BUDGET = 8;

type Props = { definition: InteractiveLabDefinition<LabState>; state: LabState; profile: CapabilityProfile; reducedMotion: boolean; traceFlowId: string | null; dispatch: (action: LabAction) => void; onPick: (pick: ScenePick) => void; onDowngrade: (reason:"context"|"performance")=>void; onUpgradeReady?:()=>void; allowProfileUpgrade?:boolean; allowPerformanceDowngrade?:boolean; review?:boolean };
function placeCamera(camera:THREE.PerspectiveCamera,pose:CameraPose){const cp=Math.cos(pose.pitch);camera.position.set(pose.target[0]+Math.sin(pose.yaw)*cp*pose.distance,pose.target[1]+Math.sin(pose.pitch)*pose.distance,pose.target[2]+Math.cos(pose.yaw)*cp*pose.distance);camera.lookAt(...pose.target);camera.updateProjectionMatrix();}

/** HIGH/STANDARD renderer. It consumes the shared render list; state/evidence remain renderer agnostic. */
export function ThreeScene({definition,state,profile,reducedMotion,traceFlowId,onPick,onDowngrade,allowPerformanceDowngrade=true,review=false}:Props){
  const host=useRef<HTMLDivElement>(null),canvas=useRef<HTMLCanvasElement|null>(null),canvasHost=useRef<HTMLDivElement>(null),runtime=useRef<{renderer:THREE.WebGLRenderer;scene:THREE.Scene;camera:THREE.PerspectiveCamera;stores:ThreeSceneStores;list:RenderList|null;plan:FramePlan|null;pose:CameraPose|null;rig:EnvironmentRig}>();
  const hasFlows=!!definition.fidelity?.flows.length;const sceneActive=useSceneActive(host,review);const {display,time}=useDisplayFidelity(definition,state,reducedMotion,hasFlows,sceneActive);
  const constraints=definition.fidelity?.camera.constraints;
  const presetId=state.fidelity?.cameraPresetId??"scene-default";const lastPreset=useRef<string|null>(null);
  const callbacks=useRef({onPick,traceFlowId,onDowngrade});callbacks.current={onPick,traceFlowId,onDowngrade};
  const refreshOverlays=useRef<()=>void>(()=>{});
  // R3 performance P1: overlays (labels, inspect buttons) rebuild at most every 120 ms or on a state change, with a
  // trailing refresh so the settled frame is always current; the frame monitor samples only while the scene is
  // actually rendering and the page is visible (no idle rAF loop, no hidden-tab sampling).
  const overlayAt=useRef(0),overlayState=useRef<LabState|null>(null),overlayTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
  const lastRenderAt=useRef(0),wakeMonitor=useRef<()=>void>(()=>{});
  useEffect(()=>()=>clearTimeout(overlayTimer.current),[]);
  useEffect(()=>{if(!allowPerformanceDowngrade||profile==="LOW"||profile==="FALLBACK_2D")return;let raf=0,previous=0,samples:number[]=[];
    const frame=(now:number)=>{if(document.hidden||now-lastRenderAt.current>250){raf=0;previous=0;return;}if(previous){const dt=now-previous;samples=recordFrameSample(samples,dt,dt<100);if(shouldDowngrade(samples,downgradeFrameBudgetMs(profile))){raf=0;callbacks.current.onDowngrade("performance");return;}}previous=now;raf=requestAnimationFrame(frame);};
    const wake=()=>{if(!raf&&!document.hidden){previous=0;raf=requestAnimationFrame(frame);}};wakeMonitor.current=wake;
    const onVisibility=()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0;previous=0;}else wake();};document.addEventListener("visibilitychange",onVisibility);wake();
    return()=>{cancelAnimationFrame(raf);wakeMonitor.current=()=>{};document.removeEventListener("visibilitychange",onVisibility);};},[profile,allowPerformanceDowngrade]);
  useEffect(()=>{const layer=canvasHost.current;if(!layer)return;/* A fresh canvas per mount: StrictMode mounts twice and the first cleanup force-loses its context (A5). */const el=document.createElement("canvas");el.className="block h-full w-full";el.dataset.labRenderer=`three@${THREE.REVISION}`;layer.appendChild(el);canvas.current=el;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({canvas:el,antialias:profile==="HIGH",alpha:true,powerPreference:profile==="HIGH"?"high-performance":"low-power"});}catch{el.remove();canvas.current=null;callbacks.current.onDowngrade("context");return;}renderer.localClippingEnabled=true;renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,profile==="HIGH"?2:1.25));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.NoToneMapping;const scene=new THREE.Scene();const daylight=definition.fidelity?.environment==="DAYLIGHT";scene.background=new THREE.Color(daylight?"#e7eef1":"#0b1223");const camera=new THREE.PerspectiveCamera(definition.scene.camera.fov,1,.1,250);scene.add(new THREE.HemisphereLight(daylight?"#ffffff":"#dbeafe",daylight?"#73816e":"#18223a",daylight?1.25:.65));const key=new THREE.DirectionalLight(daylight?"#fff7e6":"#ffffff",daylight?2.3:1.7);key.position.set(-5,10,8);scene.add(key);const fill=new THREE.DirectionalLight(daylight?"#cde7ff":"#8fb7ff",.55);fill.position.set(7,3,-6);scene.add(fill);const ground=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:daylight?"#c9d9c4":"#111a2c",roughness:1,metalness:0}));ground.rotation.x=-Math.PI/2;ground.position.y=-2.25;ground.name="environment-ground";scene.add(ground);const rig=applyEnvironmentRig(renderer,scene,key,{daylight,profile:profile==="STANDARD"?"STANDARD":"HIGH",finePointer:typeof window.matchMedia==="function"&&window.matchMedia("(pointer: fine)").matches});ground.receiveShadow=rig.shadows;const stores=createThreeSceneStores(scene,rig.shadows);runtime.current={renderer,scene,camera,stores,list:null,plan:null,pose:null,rig};
    /* A5: preventDefault so the browser may restore the context, then step straight to FALLBACK_2D. */const lose=(event:Event)=>{event.preventDefault();callbacks.current.onDowngrade("context");};el.addEventListener("webglcontextlost",lose);const resize=()=>{const w=Math.max(1,el.clientWidth),h=Math.max(1,el.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.fov=fitHorizontalFieldOfView(definition.scene.camera.fov,w/h);camera.updateProjectionMatrix();if(runtime.current?.pose)placeCamera(camera,runtime.current.pose);renderer.render(scene,camera);};const observer=new ResizeObserver(resize);if(host.current)observer.observe(host.current);resize();return()=>{observer.disconnect();el.removeEventListener("webglcontextlost",lose);disposeThreeSceneStores(stores);rig.dispose();ground.geometry.dispose();const groundMaterials=Array.isArray(ground.material)?ground.material:[ground.material as THREE.Material];groundMaterials.forEach((material)=>material.dispose());renderer.dispose();renderer.forceContextLoss();el.remove();canvas.current=null;runtime.current=undefined;};},[definition,profile]);
  useEffect(()=>{const r=runtime.current;if(!r)return;const list=buildRenderList({definition,state,profile,displayFidelity:display});r.list=list;const plan=syncThreeScene(r.stores,list,{profile:profile==="STANDARD"?"STANDARD":"HIGH",time,reducedMotion,traceFlowId});r.plan=planThreeFrame(list,{profile:profile==="STANDARD"?"STANDARD":"HIGH",traceFlowId,plan});
    const preset=list.camera??{target:[0,0,0] as [number,number,number],distance:11,yaw:0,pitch:0};if(!r.pose||lastPreset.current!==presetId){r.pose=constraints?constrainCamera(preset,constraints):preset;lastPreset.current=presetId;}let shadowPass=false;if(r.rig.shadows){const casterHash=shadowCasterHash(list);if(casterHash!==r.stores.shadowHash){r.stores.shadowHash=casterHash;r.renderer.shadowMap.needsUpdate=true;shadowPass=true;}}placeCamera(r.camera,r.pose);r.renderer.render(r.scene,r.camera);const layer=canvasHost.current;if(layer){/* Review evidence (rendererIdentity.ts): frames drawn, last-frame draw calls and the planned frame. */layer.dataset.labDrawCalls=String(r.renderer.info.render.calls);layer.dataset.labFramesRendered=String((Number(layer.dataset.labFramesRendered)||0)+1);publishFramePlan(layer,r.plan,shadowPass);}
    refreshOverlays.current=()=>{const currentList=r.list;if(!currentList)return;const projectScreen=(item:RenderItem,point:[number,number,number]=item.center)=>{const p=new THREE.Vector3(...point).project(r.camera);return{x:(p.x*.5+.5)*r.renderer.domElement.clientWidth,y:(-.5*p.y+.5)*r.renderer.domElement.clientHeight,visible:p.z<=1};};const labels=host.current?.querySelector<HTMLDivElement>("[data-three-labels]");if(labels){/* A11 label budget: highlighted parts first, then authored order, at most SCENE_LABEL_BUDGET; the rest stay in the parts list. */const labelled=currentList.items.filter(i=>i.showLabel&&i.inFocus&&!i.control&&!(narrowViewport()&&i.mobileLabel===false));const viewport={width:r.renderer.domElement.clientWidth,height:r.renderer.domElement.clientHeight};/* Only on-screen, non-overlapping labels count against the budget (R3 visual: city camera, Spillway gate over Headpond, edge fragments). */const placed=placeSceneLabels(labelled.flatMap(item=>{const at=projectScreen(item,transformPoint(item.matrix,item.labelOffset??[0,0,0]));return at.visible?[{id:item.id,text:item.label,x:at.x,y:at.y,highlighted:item.highlighted}]:[];}),viewport,SCENE_LABEL_BUDGET);labels.replaceChildren(...placed.map(label=>{const node=document.createElement("span");node.textContent=label.text;node.className="pointer-events-none absolute -translate-x-1/2 -translate-y-full whitespace-nowrap rounded bg-slate-950/75 px-2 py-0.5 text-[11px] font-semibold text-white";node.style.left=`${label.x}px`;node.style.top=`${label.y}px`;return node;}));}
    const controls=host.current?.querySelector<HTMLDivElement>("[data-three-controls]");if(controls){const focusedPartId=(document.activeElement as HTMLElement|null)?.dataset.partId;const pickable=currentList.items.filter(item=>item.selectable&&item.inFocus&&item.detail!=="decor");
      // Inspect targets: keyboard-reachable 44 px buttons that stay out of sight until hovered or focused.
      const inspect=pickable.filter(item=>!item.control).map(item=>{const at=projectScreen(item),button=document.createElement("button");button.type="button";button.dataset.partId=item.id;button.setAttribute("aria-label",`Inspect ${item.label}`);button.setAttribute("aria-pressed",String(item.highlighted));button.title=`Inspect ${item.label}`;button.className="absolute h-11 w-11 -translate-x-1/2 -translate-y-1/2 rounded-full border border-slate-900/60 bg-white/70 text-slate-900 opacity-0 hover:opacity-100 focus-visible:opacity-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-slate-900";button.textContent="?";button.style.left=`${at.x}px`;button.style.top=`${at.y}px`;button.hidden=!at.visible;button.addEventListener("click",()=>callbacks.current.onPick({kind:"item",item}));return button;});
controls.replaceChildren(...inspect);if(focusedPartId)Array.from(controls.querySelectorAll<HTMLButtonElement>("button")).find(button=>button.dataset.partId===focusedPartId)?.focus();}};
    const overlayNow=performance.now();lastRenderAt.current=overlayNow;wakeMonitor.current();clearTimeout(overlayTimer.current);
    if(overlayState.current!==state||overlayNow-overlayAt.current>=120){overlayState.current=state;overlayAt.current=overlayNow;refreshOverlays.current();}
    else overlayTimer.current=setTimeout(()=>{overlayAt.current=performance.now();refreshOverlays.current();},130);
  },[definition,state,profile,display,time,constraints,presetId,traceFlowId,reducedMotion]);
  // RX-005 A8 review probe: one worst-case frame (frustum culling off, shadow map forced) measured by renderer.info,
  // beside the shared planner. Review only; learner sessions never install it.
  useEffect(()=>{if(!review)return;const probe:ReviewFrameProbe=()=>{const r=runtime.current;if(!r?.plan)return null;const culled:THREE.Object3D[]=[];r.scene.traverse(object=>{if(object.frustumCulled){object.frustumCulled=false;culled.push(object);}});const info=r.renderer.info.render;if(r.rig.shadows)r.renderer.shadowMap.needsUpdate=true;r.renderer.render(r.scene,r.camera);const withShadow={calls:info.calls,triangles:info.triangles};r.renderer.render(r.scene,r.camera);const main={calls:info.calls,triangles:info.triangles};culled.forEach(object=>{object.frustumCulled=true;});r.renderer.render(r.scene,r.camera);return{renderer:"three",planned:r.plan,measured:{drawCalls:main.calls,triangles:main.triangles,shadowDrawCalls:withShadow.calls-main.calls,shadowTriangles:withShadow.triangles-main.triangles},programs:r.renderer.info.programs?.length??null,memory:{geometries:r.renderer.info.memory.geometries,textures:r.renderer.info.memory.textures}};};const reviewWindow=window as Window&{__labReviewFrameProbe?:ReviewFrameProbe};reviewWindow.__labReviewFrameProbe=probe;return()=>{if(reviewWindow.__labReviewFrameProbe===probe)delete reviewWindow.__labReviewFrameProbe;};},[review]);
  const pointer=useRef<{x:number;y:number;down:boolean;moved:boolean;pose:CameraPose|null}>({x:0,y:0,down:false,moved:false,pose:null});
  const onPointerDown=(event:ReactPointerEvent<HTMLDivElement>)=>{const r=runtime.current;if(!r)return;pointer.current={x:event.clientX,y:event.clientY,down:true,moved:false,pose:r.pose};event.currentTarget.setPointerCapture(event.pointerId);};
  const onPointerMove=(event:ReactPointerEvent<HTMLDivElement>)=>{const p=pointer.current,r=runtime.current;if(!p.down||!r||!p.pose)return;const dx=event.clientX-p.x,dy=event.clientY-p.y;if(Math.abs(dx)+Math.abs(dy)>3)p.moved=true;const next={...p.pose,yaw:p.pose.yaw-dx*.004,pitch:p.pose.pitch+dy*.004};r.pose=constraints?constrainCamera(next,constraints):next;placeCamera(r.camera,r.pose);r.renderer.render(r.scene,r.camera);refreshOverlays.current();};
  const onPointerUp=(event:ReactPointerEvent<HTMLDivElement>)=>{const p=pointer.current,r=runtime.current,rect=event.currentTarget.getBoundingClientRect();if(p.down&&!p.moved&&r?.list){const project=(point:[number,number,number])=>{const v=new THREE.Vector3(...point).project(r.camera);return v.z>1?null:{x:(v.x*.5+.5)*rect.width,y:(-.5*v.y+.5)*rect.height};};const pick=pickNearest(r.list,project,{x:event.clientX-rect.left,y:event.clientY-rect.top},callbacks.current.traceFlowId);if(pick)callbacks.current.onPick(pick);}pointer.current.down=false;};
  // Wheel zoom needs a non-passive native listener: React's onWheel is passive, so its preventDefault is ignored (R3P-008).
  useEffect(()=>{const layer=canvasHost.current;if(!layer)return;const onWheel=(event:WheelEvent)=>{const r=runtime.current;if(!r?.pose)return;event.preventDefault();const pose={...r.pose,distance:r.pose.distance*Math.exp(event.deltaY*.001)};r.pose=constraints?constrainCamera(pose,constraints):pose;placeCamera(r.camera,r.pose);r.renderer.render(r.scene,r.camera);refreshOverlays.current();};layer.addEventListener("wheel",onWheel,{passive:false});return()=>layer.removeEventListener("wheel",onWheel);},[constraints]);
  const onKeyDown=(event:React.KeyboardEvent<HTMLDivElement>)=>{const r=runtime.current;if(!r?.pose)return;const p={...r.pose};if(event.key==="ArrowLeft")p.yaw-=.08;else if(event.key==="ArrowRight")p.yaw+=.08;else if(event.key==="ArrowUp"&&event.shiftKey)p.target=[p.target[0],p.target[1]+.2,p.target[2]];else if(event.key==="ArrowDown"&&event.shiftKey)p.target=[p.target[0],p.target[1]-.2,p.target[2]];else if(event.key==="ArrowUp")p.pitch+=.06;else if(event.key==="ArrowDown")p.pitch-=.06;else if(event.key==="+")p.distance*=.9;else if(event.key==="-")p.distance*=1.1;else return;event.preventDefault();r.pose=constraints?constrainCamera(p,constraints):p;placeCamera(r.camera,r.pose);r.renderer.render(r.scene,r.camera);refreshOverlays.current();};
  return <div ref={host} className="relative h-[clamp(420px,62vh,640px)] w-full" aria-label="Interactive 3D lab scene"><div ref={canvasHost} data-lab-renderer={`three@${THREE.REVISION}`} className="absolute inset-0 touch-none focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-slate-900" tabIndex={0} role="application" onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={onPointerUp} onPointerCancel={()=>{pointer.current.down=false;}} onKeyDown={onKeyDown} aria-label="3D scene; drag to orbit, scroll to zoom, arrow keys to move camera"/><div data-three-labels className="pointer-events-none absolute inset-0 overflow-hidden"/><div data-three-controls className="pointer-events-none absolute inset-0 overflow-hidden [&>button]:pointer-events-auto"/></div>;
}
