"use client";

import * as THREE from "three";
import { SCENE_HEIGHT } from "./sceneLayout";
import { useEffect, useRef, type PointerEvent as ReactPointerEvent } from "react";
import type { CapabilityProfile, InteractiveLabDefinition, LabAction, LabState } from "@/lib/interactive-labs/v2/types";
import { buildRenderList, type RenderItem, type RenderList } from "@/lib/interactive-labs/v2/fidelity/renderList";
import { type CameraPose } from "@/lib/interactive-labs/v2/fidelity/presentation";
import { constrainOrbit, DEFAULT_LEG, findPreset, framedPose, tweenPose, type CameraLeg } from "@/lib/interactive-labs/v2/fidelity/camera";
import { pickNearest, type ScenePick } from "./picking";
import { useDisplayFidelity } from "./useDisplayFidelity";
import { useSceneActive } from "./useSceneActive";
import { recordFrameSample, shouldDowngrade } from "@/lib/interactive-labs/v2/fidelity/profiles";
import { downgradeFrameBudgetMs } from "@/lib/interactive-labs/v2/production/budgets";
import { fitHorizontalFieldOfView, transformPoint } from "@/lib/interactive-labs/v2/fidelity/math";
import { applyEnvironmentRig, type EnvironmentRig } from "./threeEnvironment";
import { createThreeSceneStores, disposeThreeSceneStores, shadowCasterHash, syncThreeScene, type ThreeSceneStores } from "./threeSceneSync";
import { planThreeFrame, type FramePlan } from "@/lib/interactive-labs/v2/fidelity/framePlan";
import { publishFramePlan, type ReviewFrameProbe } from "@/lib/interactive-labs/v2/review/framePlanEvidence";
import { placeSceneLabels } from "@/lib/interactive-labs/v2/fidelity/labelLayout";
import { controlTargetElements } from "./controlTargets";
import { controlAffordanceElements, controlCursor, cueElements, statusBadgeElements } from "./sceneCues";
import { ENVIRONMENT_BACKDROP } from "@/lib/interactive-labs/v2/fidelity/palette";
import { dragParameter } from "@/lib/interactive-labs/v2/fidelity/controls";

/** Matches the max-[500px] breakpoint that hides secondary (mobileLabel: false) callouts. */
const narrowViewport = () => typeof window !== "undefined" && window.innerWidth <= 500;

/** A11: at most this many part labels in the scene outside guided focus; the parts list carries the rest. */
const SCENE_LABEL_BUDGET = 8;

type Props = { definition: InteractiveLabDefinition<LabState>; state: LabState; profile: CapabilityProfile; reducedMotion: boolean; traceFlowId: string | null; dispatch: (action: LabAction) => void; onPick: (pick: ScenePick) => void; onDowngrade: (reason:"context"|"performance"|"creation")=>void; onUpgradeReady?:()=>void; allowProfileUpgrade?:boolean; allowPerformanceDowngrade?:boolean; review?:boolean; onReady?:()=>void; cameraLeg?:CameraLeg; recenter?:number; initialPose?:{presetId:string;pose:CameraPose}|null; onPoseChange?:(presetId:string,pose:CameraPose)=>void; pendingControlId?:string|null; onDragControl?:(componentId:string,t:number)=>void };
function placeCamera(camera:THREE.PerspectiveCamera,pose:CameraPose){const cp=Math.cos(pose.pitch);camera.position.set(pose.target[0]+Math.sin(pose.yaw)*cp*pose.distance,pose.target[1]+Math.sin(pose.pitch)*pose.distance,pose.target[2]+Math.cos(pose.yaw)*cp*pose.distance);camera.lookAt(...pose.target);camera.updateProjectionMatrix();}

/** HIGH/STANDARD renderer. It consumes the shared render list; state/evidence remain renderer agnostic. */
export function ThreeScene({definition,state,profile,reducedMotion,traceFlowId,onPick,onDowngrade,allowPerformanceDowngrade=true,review=false,onReady,cameraLeg,recenter=0,initialPose=null,onPoseChange,pendingControlId=null,onDragControl}:Props){
  const host=useRef<HTMLDivElement>(null),canvas=useRef<HTMLCanvasElement|null>(null),canvasHost=useRef<HTMLDivElement>(null),runtime=useRef<{renderer:THREE.WebGLRenderer;scene:THREE.Scene;camera:THREE.PerspectiveCamera;stores:ThreeSceneStores;list:RenderList|null;plan:FramePlan|null;pose:CameraPose|null;rig:EnvironmentRig;compiled:boolean;anchor:CameraPose|null;atAnchor:boolean;tween:{from:CameraPose;to:CameraPose;start:number;leg:CameraLeg}|null;tweenFrame:number}>();
  const hasFlows=!!definition.fidelity?.flows.length;const sceneActive=useSceneActive(host,review);const {display,time}=useDisplayFidelity(definition,state,reducedMotion,hasFlows,sceneActive);
  const constraints=definition.fidelity?.camera.constraints;
  const presetId=state.fidelity?.cameraPresetId??"scene-default";const lastPreset=useRef<string|null>(null),lastRecenter=useRef(recenter);
  // A16: guided steps hold the view near their preset; explore allows the lab's full limits.
  const orbitMode=useRef<"explore"|"guided">("explore");orbitMode.current=state.mode==="GUIDED"?"guided":"explore";
  const callbacks=useRef({onPick,traceFlowId,onDowngrade,onReady,cameraLeg,reducedMotion,initialPose,onPoseChange,presetId,onDragControl});callbacks.current={onPick,traceFlowId,onDowngrade,onReady,cameraLeg,reducedMotion,initialPose,onPoseChange,presetId,onDragControl};
  /** RX-005d: one eased camera leg to `to` on its own frame loop (camera moves run at the display rate, A6); reduced motion cuts. */
  const startTween=(to:CameraPose)=>{const r=runtime.current;if(!r?.pose)return;cancelAnimationFrame(r.tweenFrame);const leg=callbacks.current.cameraLeg??DEFAULT_LEG;const settle=(rt:NonNullable<typeof runtime.current>)=>{rt.tween=null;rt.atAnchor=true;refreshOverlays.current();callbacks.current.onPoseChange?.(callbacks.current.presetId,rt.pose!);};if(callbacks.current.reducedMotion||leg.durationMs<=0){r.pose=to;settle(r);return;}r.tween={from:r.pose,to,start:performance.now(),leg};let overlayAtTween=0;const step=(now:number)=>{const rt=runtime.current;if(!rt?.tween)return;const t=rt.tween;rt.pose=tweenPose(t.from,t.to,now-t.start,t.leg.durationMs,t.leg.easing,false);placeCamera(rt.camera,rt.pose);rt.renderer.render(rt.scene,rt.camera);lastRenderAt.current=now;wakeMonitor.current();if(now-t.start>=t.leg.durationMs){settle(rt);return;}if(now-overlayAtTween>120){overlayAtTween=now;refreshOverlays.current();}rt.tweenFrame=requestAnimationFrame(step);};r.tweenFrame=requestAnimationFrame(step);};
  /** A16: the learner's orbit, zoom and pan, held inside the lab's limits around the current preset. */
  const orbitTo=(pose:CameraPose)=>{const r=runtime.current;if(!r)return;if(r.tween){cancelAnimationFrame(r.tweenFrame);r.tween=null;}r.pose=constraints&&r.anchor?constrainOrbit(pose,constraints,{anchor:r.anchor,mode:orbitMode.current}):pose;r.atAnchor=false;placeCamera(r.camera,r.pose);r.renderer.render(r.scene,r.camera);refreshOverlays.current();callbacks.current.onPoseChange?.(callbacks.current.presetId,r.pose);};
  const refreshOverlays=useRef<()=>void>(()=>{});
  // R3 performance P1: overlays (labels, inspect buttons) rebuild at most every 120 ms or on a state change, with a
  // trailing refresh so the settled frame is always current; the frame monitor samples only while the scene is
  // actually rendering and the page is visible (no idle rAF loop, no hidden-tab sampling).
  const overlayAt=useRef(0),overlayState=useRef<LabState|null>(null),overlayTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
  const lastRenderAt=useRef(0),wakeMonitor=useRef<()=>void>(()=>{});
  useEffect(()=>()=>clearTimeout(overlayTimer.current),[]);
  useEffect(()=>{if(!allowPerformanceDowngrade||profile==="LOW"||profile==="FALLBACK_2D")return;let raf=0,previous=0,samples:number[]=[];
    const frame=(now:number)=>{if(document.hidden||now-lastRenderAt.current>250){raf=0;previous=0;return;}if(previous){const dt=now-previous;samples=recordFrameSample(samples,dt,dt<100);if(shouldDowngrade(samples,downgradeFrameBudgetMs(profile))){raf=0;callbacks.current.onDowngrade("performance");return;}}previous=now;raf=requestAnimationFrame(frame);};
    const wake=()=>{if(!raf&&!document.hidden){previous=0;raf=requestAnimationFrame(frame);}};wakeMonitor.current=wake;
    const onVisibility=()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0;previous=0;}else wake();};document.addEventListener("visibilitychange",onVisibility);wake();
    return()=>{cancelAnimationFrame(raf);wakeMonitor.current=()=>{};document.removeEventListener("visibilitychange",onVisibility);};},[profile,allowPerformanceDowngrade]);
  useEffect(()=>{const layer=canvasHost.current;if(!layer)return;/* A fresh canvas per mount: StrictMode mounts twice and the first cleanup force-loses its context (A5). */const el=document.createElement("canvas");el.className="block h-full w-full";el.dataset.labRenderer=`three@${THREE.REVISION}`;layer.appendChild(el);canvas.current=el;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({canvas:el,antialias:profile==="HIGH",alpha:true,powerPreference:profile==="HIGH"?"high-performance":"low-power"});}/* R4 P1-3: three.js needs WebGL2; a device that cannot create it still has the LOW pass. */catch{el.remove();canvas.current=null;callbacks.current.onDowngrade("creation");return;}renderer.localClippingEnabled=true;renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,profile==="HIGH"?2:1.25));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.NoToneMapping;const scene=new THREE.Scene();const daylight=definition.fidelity?.environment==="DAYLIGHT";scene.background=new THREE.Color(ENVIRONMENT_BACKDROP[definition.fidelity?.environment??"STUDIO"]);const camera=new THREE.PerspectiveCamera(definition.scene.camera.fov,1,.1,250);scene.add(new THREE.HemisphereLight(daylight?"#ffffff":"#dbeafe",daylight?"#73816e":"#18223a",daylight?1.25:.65));const key=new THREE.DirectionalLight(daylight?"#fff7e6":"#ffffff",daylight?2.3:1.7);key.position.set(-5,10,8);scene.add(key);const fill=new THREE.DirectionalLight(daylight?"#cde7ff":"#8fb7ff",.55);fill.position.set(7,3,-6);scene.add(fill);const ground=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:daylight?"#c9d9c4":"#111a2c",roughness:1,metalness:0}));ground.rotation.x=-Math.PI/2;ground.position.y=-2.25;ground.name="environment-ground";scene.add(ground);const rig=applyEnvironmentRig(renderer,scene,key,{daylight,profile:profile==="STANDARD"?"STANDARD":"HIGH",targetBox:definition.fidelity?.camera.constraints.targetBox});ground.receiveShadow=rig.shadows;const stores=createThreeSceneStores(scene,rig.shadows);runtime.current={renderer,scene,camera,stores,list:null,plan:null,pose:null,rig,compiled:false,anchor:null,atAnchor:true,tween:null,tweenFrame:0};/* A5 review evidence: live renderers across remounts. */const reviewWindow=window as Window&{__labReviewLiveRenderers?:number};if(review)reviewWindow.__labReviewLiveRenderers=(reviewWindow.__labReviewLiveRenderers??0)+1;
    /* A5: preventDefault so the browser may restore the context, then step straight to FALLBACK_2D. */const lose=(event:Event)=>{event.preventDefault();callbacks.current.onDowngrade("context");};el.addEventListener("webglcontextlost",lose);const resize=()=>{const w=Math.max(1,el.clientWidth),h=Math.max(1,el.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.fov=fitHorizontalFieldOfView(definition.scene.camera.fov,w/h);camera.updateProjectionMatrix();const rt=runtime.current;/* RX-005d: an un-orbited framed preset refits to the new aspect (phone rotation, panel resize). */if(rt?.atAnchor&&!rt.tween&&rt.list&&definition.fidelity&&rt.pose){rt.anchor=framedPose(definition.fidelity,findPreset(definition.fidelity,callbacks.current.presetId),rt.list.items,definition.scene.camera.fov,w/h);rt.pose=rt.anchor;}if(rt?.pose)placeCamera(camera,rt.pose);renderer.render(scene,camera);};const observer=new ResizeObserver(resize);if(host.current)observer.observe(host.current);resize();return()=>{cancelAnimationFrame(runtime.current?.tweenFrame??0);observer.disconnect();el.removeEventListener("webglcontextlost",lose);disposeThreeSceneStores(stores);rig.dispose();ground.geometry.dispose();const groundMaterials=Array.isArray(ground.material)?ground.material:[ground.material as THREE.Material];groundMaterials.forEach((material)=>material.dispose());renderer.dispose();renderer.forceContextLoss();if(review)reviewWindow.__labReviewLiveRenderers=(reviewWindow.__labReviewLiveRenderers??1)-1;el.remove();canvas.current=null;runtime.current=undefined;};},[definition,profile,review]);
  useEffect(()=>{const r=runtime.current;if(!r)return;const list=buildRenderList({definition,state,profile,displayFidelity:display,pendingControlId});r.list=list;const plan=syncThreeScene(r.stores,list,{profile:profile==="STANDARD"?"STANDARD":"HIGH",time,reducedMotion,traceFlowId});r.plan=planThreeFrame(list,{profile:profile==="STANDARD"?"STANDARD":"HIGH",traceFlowId,plan});
    const spec=definition.fidelity,aspect=Math.max(1,r.renderer.domElement.clientWidth)/Math.max(1,r.renderer.domElement.clientHeight);const anchor:CameraPose=spec?framedPose(spec,findPreset(spec,presetId),list.items,definition.scene.camera.fov,aspect):list.camera??{target:[0,0,0],distance:11,yaw:0,pitch:0};r.anchor=anchor;
    // A18 continuity: a renderer swap keeps the learner's view of the same preset; a preset change or Recentre eases to the new framing.
    if(!r.pose){const carried=callbacks.current.initialPose;r.pose=carried&&carried.presetId===presetId?carried.pose:anchor;r.atAnchor=!(carried&&carried.presetId===presetId);lastPreset.current=presetId;lastRecenter.current=recenter;}
    else if(lastPreset.current!==presetId||lastRecenter.current!==recenter){lastPreset.current=presetId;lastRecenter.current=recenter;startTween(anchor);}
    else if(r.atAnchor&&!r.tween)r.pose=anchor;let shadowPass=false;if(r.rig.shadows){const casterHash=shadowCasterHash(list);if(casterHash!==r.stores.shadowHash){r.stores.shadowHash=casterHash;r.renderer.shadowMap.needsUpdate=true;shadowPass=true;}}placeCamera(r.camera,r.pose);/* A9: review mode compiles every program before the first frame, so captures never catch a half-compiled scene. */if(review&&!r.compiled){r.renderer.compile(r.scene,r.camera);r.compiled=true;}r.renderer.render(r.scene,r.camera);const layer=canvasHost.current;if(layer&&!layer.dataset.labSceneReady){layer.dataset.labSceneReady="true";callbacks.current.onReady?.();}if(layer){/* Review evidence (rendererIdentity.ts): frames drawn, last-frame draw calls and the planned frame. */layer.dataset.labDrawCalls=String(r.renderer.info.render.calls);layer.dataset.labFramesRendered=String((Number(layer.dataset.labFramesRendered)||0)+1);publishFramePlan(layer,r.plan,shadowPass);}
    refreshOverlays.current=()=>{const currentList=r.list;if(!currentList)return;const projectScreen=(item:RenderItem,point:[number,number,number]=item.center)=>{const p=new THREE.Vector3(...point).project(r.camera);return{x:(p.x*.5+.5)*r.renderer.domElement.clientWidth,y:(-.5*p.y+.5)*r.renderer.domElement.clientHeight,visible:p.z<=1};};const labels=host.current?.querySelector<HTMLDivElement>("[data-three-labels]");if(labels){/* A11 label budget: highlighted parts first, then authored order, at most SCENE_LABEL_BUDGET; the rest stay in the parts list. */const labelled=currentList.items.filter(i=>i.showLabel&&i.inFocus&&!i.control&&!(narrowViewport()&&i.mobileLabel===false));const viewport={width:r.renderer.domElement.clientWidth,height:r.renderer.domElement.clientHeight};/* Only on-screen, non-overlapping labels count against the budget (R3 visual: city camera, Spillway gate over Headpond, edge fragments). */const placed=placeSceneLabels(labelled.flatMap(item=>{const at=projectScreen(item,transformPoint(item.matrix,item.labelOffset??[0,0,0]));return at.visible?[{id:item.id,text:item.label,x:at.x,y:at.y,highlighted:item.highlighted,critical:!!item.labelCritical}]:[];}),viewport,SCENE_LABEL_BUDGET);labels.replaceChildren(...placed.map(label=>{const node=document.createElement("span");node.textContent=label.text;node.dataset.labSceneLabel=label.id;node.className="pointer-events-none absolute -translate-x-1/2 -translate-y-full whitespace-nowrap rounded bg-slate-950/75 px-2 py-0.5 text-[11px] font-semibold text-white";node.style.left=`${Math.round(label.x)}px`;node.style.top=`${Math.round(label.y)}px`;return node;}));}
    /* A15: under reduced motion, static direction cues on active flows, moving surfaces and emitters. */const cueLayer=host.current?.querySelector<HTMLDivElement>("[data-three-cues]");const toScreen=(point:[number,number,number])=>{const p=new THREE.Vector3(...point).project(r.camera);return p.z>1?null:{x:(p.x*.5+.5)*r.renderer.domElement.clientWidth,y:(-.5*p.y+.5)*r.renderer.domElement.clientHeight};};if(cueLayer)cueLayer.replaceChildren(...(callbacks.current.reducedMotion?cueElements(currentList.cues,toScreen):[]),/* A19 / G3: status glyphs beside every lamp. */...statusBadgeElements(currentList.items,toScreen),/* A14 control affordance and the pending Confirm? label. */...controlAffordanceElements(currentList.items,toScreen));
    const controls=host.current?.querySelector<HTMLDivElement>("[data-three-controls]");if(controls){const focusedPartId=(document.activeElement as HTMLElement|null)?.dataset.partId;const pickable=currentList.items.filter(item=>item.selectable&&item.inFocus&&item.detail!=="decor");
      // Inspect targets: keyboard-reachable 44 px buttons that stay out of sight until hovered or focused.
      const inspect=pickable.filter(item=>!item.control).map(item=>{const at=projectScreen(item),button=document.createElement("button");button.type="button";button.dataset.partId=item.id;button.setAttribute("aria-label",`Inspect ${item.label}`);button.setAttribute("aria-pressed",String(item.highlighted));button.title=`Inspect ${item.label}`;button.className="absolute h-11 w-11 -translate-x-1/2 -translate-y-1/2 rounded-full border border-slate-900/60 bg-white/70 text-slate-900 opacity-0 hover:opacity-100 focus-visible:opacity-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-slate-900";button.textContent="?";button.style.left=`${Math.round(at.x)}px`;button.style.top=`${Math.round(at.y)}px`;button.hidden=!at.visible;button.addEventListener("click",()=>callbacks.current.onPick({kind:"item",item}));return button;});
controls.replaceChildren(...inspect, ...controlTargetElements(currentList.items,toScreen,r.renderer.domElement.clientWidth,r.renderer.domElement.clientHeight,(pick)=>callbacks.current.onPick(pick),r.renderer.domElement.getBoundingClientRect().top,r.renderer.domElement.getBoundingClientRect().left));if(focusedPartId)Array.from(controls.querySelectorAll<HTMLButtonElement>("button")).find(button=>button.dataset.partId===focusedPartId)?.focus();}};
    const overlayNow=performance.now();lastRenderAt.current=overlayNow;wakeMonitor.current();clearTimeout(overlayTimer.current);
    if(overlayState.current!==state||overlayNow-overlayAt.current>=120){overlayState.current=state;overlayAt.current=overlayNow;refreshOverlays.current();}
    else overlayTimer.current=setTimeout(()=>{overlayAt.current=performance.now();refreshOverlays.current();},130);
  },[definition,state,profile,display,time,constraints,presetId,traceFlowId,reducedMotion,recenter,pendingControlId]);
  // RX-005 A8 review probe: one worst-case frame (frustum culling off, shadow map forced) measured by renderer.info,
  // beside the shared planner. Review only; learner sessions never install it.
  useEffect(()=>{if(!review)return;const probe:ReviewFrameProbe=()=>{const r=runtime.current;if(!r?.plan)return null;const culled:THREE.Object3D[]=[];r.scene.traverse(object=>{if(object.frustumCulled){object.frustumCulled=false;culled.push(object);}});const info=r.renderer.info.render;if(r.rig.shadows)r.renderer.shadowMap.needsUpdate=true;r.renderer.render(r.scene,r.camera);const withShadow={calls:info.calls,triangles:info.triangles};r.renderer.render(r.scene,r.camera);const main={calls:info.calls,triangles:info.triangles};culled.forEach(object=>{object.frustumCulled=true;});r.renderer.render(r.scene,r.camera);return{renderer:"three",planned:r.plan,measured:{drawCalls:main.calls,triangles:main.triangles,shadowDrawCalls:withShadow.calls-main.calls,shadowTriangles:withShadow.triangles-main.triangles},programs:r.renderer.info.programs?.length??null,memory:{geometries:r.renderer.info.memory.geometries,textures:r.renderer.info.memory.textures}};};const reviewWindow=window as Window&{__labReviewFrameProbe?:ReviewFrameProbe};reviewWindow.__labReviewFrameProbe=probe;return()=>{if(reviewWindow.__labReviewFrameProbe===probe)delete reviewWindow.__labReviewFrameProbe;};},[review]);
  const pointer=useRef<{x:number;y:number;down:boolean;moved:boolean;pose:CameraPose|null;drag:RenderItem|null}>({x:0,y:0,down:false,moved:false,pose:null,drag:null});
  const screenOf=(rect:DOMRect)=>(point:[number,number,number])=>{const r=runtime.current;if(!r)return null;const v=new THREE.Vector3(...point).project(r.camera);return v.z>1?null:{x:(v.x*.5+.5)*rect.width,y:(-.5*v.y+.5)*rect.height};};
  const onPointerDown=(event:ReactPointerEvent<HTMLDivElement>)=>{const r=runtime.current;if(!r)return;const rect=event.currentTarget.getBoundingClientRect();
    // A14: a press on a drag-variable control part drags the control along its axis instead of orbiting.
    const hit=r.list?pickNearest(r.list,screenOf(rect),{x:event.clientX-rect.left,y:event.clientY-rect.top},null):null;const drag=hit?.kind==="item"&&hit.item.control?.dragAxis?hit.item:null;
    pointer.current={x:event.clientX,y:event.clientY,down:true,moved:false,pose:r.pose,drag};event.currentTarget.setPointerCapture(event.pointerId);};
  const onPointerMove=(event:ReactPointerEvent<HTMLDivElement>)=>{const p=pointer.current,r=runtime.current;if(!p.down&&r?.list&&event.pointerType==="mouse"){/* A14 cursor */const rect=event.currentTarget.getBoundingClientRect(),hit=pickNearest(r.list,screenOf(rect),{x:event.clientX-rect.left,y:event.clientY-rect.top},null);event.currentTarget.style.cursor=controlCursor(hit?.kind==="item"?hit.item.control:undefined);}if(!p.down||!r||!p.pose)return;const dx=event.clientX-p.x,dy=event.clientY-p.y;if(Math.abs(dx)+Math.abs(dy)>3)p.moved=true;
    /* A14 dead-zone: a drag dispatches only after a deliberate move, so a tap never jumps the value. */if(p.drag?.control?.dragAxis){if(!p.moved)return;const rect=event.currentTarget.getBoundingClientRect(),project=screenOf(rect),[a,b]=p.drag.control.dragAxis,start=project(a),end=project(b);if(start&&end)callbacks.current.onDragControl?.(p.drag.id,dragParameter(start,end,{x:event.clientX-rect.left,y:event.clientY-rect.top}));return;}
    orbitTo({...p.pose,yaw:p.pose.yaw-dx*.004,pitch:p.pose.pitch+dy*.004});};
  const onPointerUp=(event:ReactPointerEvent<HTMLDivElement>)=>{const p=pointer.current,r=runtime.current,rect=event.currentTarget.getBoundingClientRect();if(p.down&&!p.moved&&r?.list){const project=(point:[number,number,number])=>{const v=new THREE.Vector3(...point).project(r.camera);return v.z>1?null:{x:(v.x*.5+.5)*rect.width,y:(-.5*v.y+.5)*rect.height};};const pick=pickNearest(r.list,project,{x:event.clientX-rect.left,y:event.clientY-rect.top},callbacks.current.traceFlowId);if(pick)callbacks.current.onPick(pick);}pointer.current.down=false;};
  const orbitRef=useRef(orbitTo);orbitRef.current=orbitTo;
  // Wheel zoom needs a non-passive native listener: React's onWheel is passive, so its preventDefault is ignored (R3P-008).
  useEffect(()=>{const layer=canvasHost.current;if(!layer)return;const onWheel=(event:WheelEvent)=>{const r=runtime.current;if(!r?.pose)return;event.preventDefault();orbitRef.current({...r.pose,distance:r.pose.distance*Math.exp(event.deltaY*.001)});};layer.addEventListener("wheel",onWheel,{passive:false});return()=>layer.removeEventListener("wheel",onWheel);},[constraints]);
  const onKeyDown=(event:React.KeyboardEvent<HTMLDivElement>)=>{const r=runtime.current;if(!r?.pose)return;const p={...r.pose};/* Shift+arrows pan, which only moves the target when the lab declares a target box (A16). */if(event.key==="ArrowLeft"&&event.shiftKey)p.target=[p.target[0]-.2,p.target[1],p.target[2]];else if(event.key==="ArrowRight"&&event.shiftKey)p.target=[p.target[0]+.2,p.target[1],p.target[2]];else if(event.key==="ArrowLeft")p.yaw-=.08;else if(event.key==="ArrowRight")p.yaw+=.08;else if(event.key==="ArrowUp"&&event.shiftKey)p.target=[p.target[0],p.target[1]+.2,p.target[2]];else if(event.key==="ArrowDown"&&event.shiftKey)p.target=[p.target[0],p.target[1]-.2,p.target[2]];else if(event.key==="ArrowUp")p.pitch+=.06;else if(event.key==="ArrowDown")p.pitch-=.06;else if(event.key==="+")p.distance*=.9;else if(event.key==="-")p.distance*=1.1;else return;event.preventDefault();orbitTo(p);};
  return <div ref={host} className={`relative ${SCENE_HEIGHT} w-full`} aria-label="Interactive 3D lab scene"><div ref={canvasHost} data-lab-renderer={`three@${THREE.REVISION}`} className="absolute inset-0 touch-none focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-slate-900" tabIndex={0} role="application" onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={onPointerUp} onPointerCancel={()=>{pointer.current.down=false;}} onKeyDown={onKeyDown} aria-label="3D scene; drag to orbit, scroll to zoom, arrow keys to move camera"/><div data-three-labels className="pointer-events-none absolute inset-0 overflow-hidden"/><div data-three-cues aria-hidden="true" className="pointer-events-none absolute inset-0 overflow-hidden"/><div data-three-controls className="pointer-events-none absolute inset-0 overflow-hidden [&>button]:pointer-events-auto"/></div>;
}
