"use client";

import { useEffect, useRef } from "react";
import type { CapabilityProfile, InteractiveLabDefinition, LabAction, LabState } from "@/lib/interactive-labs/v2/types";

type Props = { definition: InteractiveLabDefinition<LabState>; state: LabState; profile: CapabilityProfile; dispatch: (action: LabAction) => void };

const vertexShader = `attribute vec3 position; attribute vec3 color; uniform mat4 matrix; varying vec3 vColor; void main(){gl_Position=matrix*vec4(position,1.0);vColor=color;}`;
const fragmentShader = `precision mediump float; varying vec3 vColor; uniform float alpha; void main(){vec3 light=normalize(vec3(-.35,.7,1.0)); float shade=.52+.48*max(dot(normalize(vec3(0,0,1)),light),0.0); gl_FragColor=vec4(vColor*shade,alpha);}`;

function hex(value: string): [number, number, number] { const n = Number.parseInt(value.replace("#", ""), 16); return [(n >> 16 & 255) / 255, (n >> 8 & 255) / 255, (n & 255) / 255]; }
function multiply(a: number[], b: number[]): number[] { const o = new Array(16).fill(0); for (let r = 0; r < 4; r++) for (let c = 0; c < 4; c++) for (let k = 0; k < 4; k++) o[c * 4 + r] += a[k * 4 + r] * b[c * 4 + k]; return o; }
function perspective(fov: number, aspect: number, near: number, far: number): number[] { const f = 1 / Math.tan(fov * Math.PI / 360), nf = 1 / (near - far); return [f / aspect, 0, 0, 0, 0, f, 0, 0, 0, 0, (far + near) * nf, -1, 0, 0, 2 * far * near * nf, 0]; }
function translate(x: number, y: number, z: number): number[] { return [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, x, y, z, 1]; }
function rotate(x: number, y: number, z: number): number[] { const sx = Math.sin(x), cx = Math.cos(x), sy = Math.sin(y), cy = Math.cos(y), sz = Math.sin(z), cz = Math.cos(z); return [cy * cz, cy * sz, -sy, 0, sx * sy * cz - cx * sz, sx * sy * sz + cx * cz, sx * cy, 0, cx * sy * cz + sx * sz, cx * sy * sz - sx * cz, cx * cy, 0, 0, 0, 0, 1]; }
function mesh(kind: string, low: boolean): { positions: number[]; colors: number[] } {
  const p: number[] = [], c: number[] = []; const push = (a: number[], b: number[], color: number[]) => { p.push(...a, ...b, ...b); c.push(...color, ...color, ...color); };
  const face = (a: number[], b: number[], d: number[], e: number[], color: number[]) => { p.push(...a, ...b, ...d, ...a, ...d, ...e); c.push(...color, ...color, ...color, ...color, ...color, ...color); };
  if (kind === "cube" || kind === "rectangular-prism") { const x = kind === "cube" ? 1 : 1.25, y = kind === "cube" ? 1 : .82, z = kind === "cube" ? 1 : .72; const v = [[-x,-y,-z],[x,-y,-z],[x,y,-z],[-x,y,-z],[-x,-y,z],[x,-y,z],[x,y,z],[-x,y,z]]; const faces = [[0,1,2,3],[4,7,6,5],[0,4,5,1],[3,2,6,7],[1,5,6,2],[0,3,7,4]]; faces.forEach((f,i)=>face(v[f[0]],v[f[1]],v[f[2]],v[f[3]], [.18+i*.09,.48+i*.05,.7-i*.06])); }
  else if (kind === "sphere") { const n = low ? 10 : 18, m = low ? 6 : 12; for (let j=0;j<m;j++){const a=Math.PI*j/m,b=Math.PI*(j+1)/m;for(let i=0;i<n;i++){const c1=2*Math.PI*i/n,c2=2*Math.PI*(i+1)/n;const q=(t:number,u:number)=>[Math.sin(t)*Math.cos(u),Math.cos(t),Math.sin(t)*Math.sin(u)];face(q(a,c1),q(a,c2),q(b,c2),q(b,c1),[.25,.55,.95]);}} }
  else { const n = low ? 16 : 28, top = kind === "cone" ? 1 : 1; for(let i=0;i<n;i++){const a=2*Math.PI*i/n,b=2*Math.PI*(i+1)/n;const a0=[Math.cos(a),-1,Math.sin(a)],b0=[Math.cos(b),-1,Math.sin(b)],a1=kind === "cone"?[0,top,0]:[Math.cos(a),top,Math.sin(a)],b1=kind === "cone"?[0,top,0]:[Math.cos(b),top,Math.sin(b)];face(a0,b0,b1,a1,kind === "cone"?[.55,.42,.9]:[.95,.45,.28]);}}
  return { positions: p, colors: c };
}

export function WebGLScene({ definition, state, profile, dispatch }: Props) {
  const canvas = useRef<HTMLCanvasElement>(null); const drag = useRef({ x: 0, y: 0, active: false });
  useEffect(() => { const el = canvas.current; if (!el) return; const gl = el.getContext("webgl", { antialias: profile === "HIGH", alpha: true }); if (!gl) return;
    const compile = (type: number, source: string) => { const s=gl.createShader(type)!; gl.shaderSource(s,source); gl.compileShader(s); return s; }; const program=gl.createProgram()!; gl.attachShader(program,compile(gl.VERTEX_SHADER,vertexShader));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,fragmentShader));gl.linkProgram(program);gl.useProgram(program);
    const position=gl.getAttribLocation(program,"position"), color=gl.getAttribLocation(program,"color"), matrix=gl.getUniformLocation(program,"matrix"), alpha=gl.getUniformLocation(program,"alpha"); const start=performance.now();
    let frame = 0; const draw=()=>{ const dpr=Math.min(window.devicePixelRatio||1,profile==="LOW"?1:2), w=el.clientWidth*dpr,h=el.clientHeight*dpr; if(el.width!==w||el.height!==h){el.width=w;el.height=h;}gl.viewport(0,0,w,h);gl.enable(gl.DEPTH_TEST);gl.clearColor(.035,.055,.11,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT); const view=translate(0,0,-11), proj=perspective(42,w/h,.1,100), t=(performance.now()-start)/1000;
      definition.scene.objects.forEach((object,index)=>{const raw=mesh(object.geometry,profile==="LOW"), pos=gl.createBuffer()!,col=gl.createBuffer()!;gl.bindBuffer(gl.ARRAY_BUFFER,pos);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(raw.positions),gl.STATIC_DRAW);gl.enableVertexAttribArray(position);gl.vertexAttribPointer(position,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,col);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(raw.colors),gl.STATIC_DRAW);gl.enableVertexAttribArray(color);gl.vertexAttribPointer(color,3,gl.FLOAT,false,0,0);const r=state.rotations[object.id]??object.transform.rotation;const pulse=state.selectedObjectId===object.id&&profile!=="LOW"?Math.sin(t*4)*.035:0;const s=object.transform.scale.map(v=>v+pulse);const model=multiply(translate(object.transform.position[0],object.transform.position[1],object.transform.position[2]),multiply(rotate(r[0],r[1],r[2]),[s[0],0,0,0,0,s[1],0,0,0,0,s[2],0,0,0,0,1]));gl.uniformMatrix4fv(matrix,false,new Float32Array(multiply(proj,multiply(view,model))));gl.uniform1f(alpha,state.selectedObjectId===object.id?.98:.9);gl.drawArrays(gl.TRIANGLES,0,raw.positions.length/3);gl.deleteBuffer(pos);gl.deleteBuffer(col);}); frame=requestAnimationFrame(draw);}; frame=requestAnimationFrame(draw); return()=>cancelAnimationFrame(frame); },[definition,state,profile]);
  return <canvas ref={canvas} aria-label="Interactive 3D lab scene" className="h-full w-full touch-none" onPointerDown={(e)=>{drag.current={x:e.clientX,y:e.clientY,active:true};(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);}} onPointerMove={(e)=>{if(!drag.current.active)return;const dx=e.clientX-drag.current.x,dy=e.clientY-drag.current.y;drag.current={x:e.clientX,y:e.clientY,active:true};const target=state.selectedObjectId??definition.scene.objects[2]?.id;if(target)dispatch({type:"rotate",objectId:target,delta:[dx*.012,dy*.012]});}} onPointerUp={()=>{drag.current.active=false;}} onClick={(e)=>{const rect=e.currentTarget.getBoundingClientRect(), index=Math.max(0,Math.min(definition.scene.objects.length-1,Math.floor(((e.clientX-rect.left)/rect.width)*definition.scene.objects.length)));dispatch({type:"select",objectId:definition.scene.objects[index].id});}} />;
}
