import type { GeometryKind, Transform, MaterialSpec } from "../../types";
import type { ComponentDefinition } from "../types";
import type { InstructionalGeometryVariants, ParametricDescriptor } from "../geometry/types";

export type KitPart = Pick<ComponentDefinition, "id" | "label" | "geometry" | "transform" | "material" | "geometryVariants">;
type KitOptions = { id: string; label: string; transform: Transform; color: string; geometry: GeometryKind; variants: InstructionalGeometryVariants };
const material = (color: string): MaterialSpec => ({ color, roughness: 0.58, metalness: 0.22 });
/** A reusable declarative component boundary for kit parts. Kits contain no lab state or simulation rules. */
export function kitPart(options: KitOptions): KitPart { return { id: options.id, label: options.label, geometry: options.geometry, transform: options.transform, material: material(options.color), geometryVariants: options.variants }; }
const variants = (high: ParametricDescriptor, standard: ParametricDescriptor, low: ParametricDescriptor, label: string): InstructionalGeometryVariants => ({ HIGH: high, STANDARD: high === standard ? { kind:"sameAs", profile:"HIGH" } : standard, LOW: low, FALLBACK_2D: { kind: "polygon", points: [[-1,-0.6],[0.5,-0.6],[1,0],[0.5,0.6],[-1,0.6]], semanticLabel: label } });
export function pipeKit(options: Omit<KitOptions,"geometry"|"variants"> & { points: readonly [number,number,number][]; radius: number }): KitPart { return kitPart({ ...options, geometry: "cylinder", variants: variants({kind:"sweep",points:options.points,radius:options.radius,radialSegments:16},{kind:"sweep",points:options.points,radius:options.radius,radialSegments:10},{kind:"sweep",points:options.points,radius:options.radius,radialSegments:6},options.label) }); }
export function generatorHousingKit(options: Omit<KitOptions,"geometry"|"variants"> & { radius: number; height: number }): KitPart { const profile: readonly (readonly [number,number])[] = [[options.radius*0.72,-options.height/2],[options.radius,-options.height*0.35],[options.radius,options.height*0.35],[options.radius*0.72,options.height/2]]; return kitPart({ ...options, geometry:"cylinder", variants:variants({kind:"lathe",profile,radialSegments:48},{kind:"lathe",profile,radialSegments:32},{kind:"lathe",profile,radialSegments:12},options.label) }); }
export function structuralSupportKit(options: Omit<KitOptions,"geometry"|"variants"> & { width: number; height: number; depth: number }): KitPart { const {width:w,height:h,depth:d}=options;return kitPart({...options,geometry:"box",variants:variants({kind:"extrude",contour:[[-w/2,-h/2],[w/2,-h/2],[w/2,h/2],[-w/2,h/2]],depth:d},{kind:"extrude",contour:[[-w/2,-h/2],[w/2,-h/2],[w/2,h/2],[-w/2,h/2]],depth:d},{kind:"extrude",contour:[[-w/2,-h/2],[w/2,-h/2],[w/2,h/2],[-w/2,h/2]],depth:d},options.label)}); }
export function waterChannelKit(options: Omit<KitOptions,"geometry"|"variants"> & { points: readonly [number,number,number][]; width: number }): KitPart { const transforms=options.points.slice(0,-1).map((a,index)=>{const b=options.points[index+1],dx=b[0]-a[0],dz=b[2]-a[2];return{position:[(a[0]+b[0])/2,(a[1]+b[1])/2,(a[2]+b[2])/2] as [number,number,number],rotation:[0,Math.atan2(dx,dz),0] as [number,number,number],scale:[1,1,Math.hypot(dx,dz)] as [number,number,number]};});const channel:ParametricDescriptor={kind:"scatter",seed:11,prototype:{kind:"extrude",contour:[[-options.width/2,-.1],[-options.width/2,.1],[-options.width/2+.04,.1],[-options.width/2+.04,-.06],[options.width/2-.04,-.06],[options.width/2-.04,.1],[options.width/2,.1],[options.width/2,-.1]],depth:1},transforms};return kitPart({...options,geometry:"box",variants:variants(channel,channel,channel,options.label)}); }
export function gateValveKit(options: Omit<KitOptions,"geometry"|"variants"> & { width:number;height:number;depth:number }): KitPart { const {width:w,height:h,depth:d}=options;const e:ParametricDescriptor={kind:"extrude",contour:[[-w/2,-h/2],[w/2,-h/2],[w/2,h/2],[-w/2,h/2]],depth:d};return kitPart({...options,geometry:"box",variants:variants(e,e,e,options.label)}); }

const transformAt = (base: Transform, position: [number,number,number], rotation: [number,number,number] = [0,0,0], scale: [number,number,number] = [1,1,1]): Transform => ({ position: [base.position[0]+position[0],base.position[1]+position[1],base.position[2]+position[2]], rotation: [base.rotation[0]+rotation[0],base.rotation[1]+rotation[1],base.rotation[2]+rotation[2]], scale: [base.scale[0]*scale[0],base.scale[1]*scale[1],base.scale[2]*scale[2]] });

/** A generic runner assembly composed from a hub lathe and deterministic blade scatter. */
export function bladedRunnerKit(options: Omit<KitOptions,"geometry"|"variants"> & { radius:number; bladeCount?:number }): KitPart[] {
  const count=options.bladeCount??8, blades=Array.from({length:count},(_,i)=>({position:[options.radius*.55,0,0] as [number,number,number],rotation:[0,2*Math.PI*i/count,0] as [number,number,number],scale:[options.radius*.9,.12,.18] as [number,number,number]}));
  const hubProfile: readonly (readonly [number,number])[]=[[0,-.18],[options.radius*.35,-.12],[options.radius*.35,.12],[0,.18]];
  const bladePrototype: ParametricDescriptor={kind:"extrude",contour:[[0,-.45],[1,-.22],[1,.22],[0,.45]],depth:.12};
  const bladeScatter: ParametricDescriptor={kind:"scatter",seed:17,prototype:bladePrototype,transforms:blades};
  return [kitPart({...options,id:`${options.id}-hub`,label:`${options.label} hub`,geometry:"cylinder",variants:variants({kind:"lathe",profile:hubProfile,radialSegments:48},{kind:"lathe",profile:hubProfile,radialSegments:32},{kind:"lathe",profile:hubProfile,radialSegments:12},`${options.label} hub`)}),kitPart({...options,id:`${options.id}-blades`,label:`${options.label} blades`,geometry:"box",variants:variants(bladeScatter,bladeScatter,{...bladeScatter,prototype:{...bladePrototype}},`${options.label} blades`)})];
}

export function rotatingMachineStackKit(options: Omit<KitOptions,"geometry"|"variants"> & { radius:number;height:number }): KitPart[] {
  const runner=bladedRunnerKit({...options,id:`${options.id}-runner`,label:"Runner",radius:options.radius*.7,transform:transformAt(options.transform,[0,-options.height*.28,0])});
  const shaft=pipeKit({id:`${options.id}-shaft`,label:"Shaft",transform:transformAt(options.transform,[0,0,0],[0,0,0],[.12,options.height*.32,.12]),color:options.color,points:[[0,-1,0],[0,1,0]],radius:1});
  const generator=generatorHousingKit({...options,id:`${options.id}-generator`,label:"Generator",radius:options.radius,height:options.height*.48,transform:transformAt(options.transform,[0,options.height*.32,0])});
  return [...runner,shaft,generator];
}

export function selectorPostKit(options: Omit<KitOptions,"geometry"|"variants"> & { radius:number;height:number }): KitPart { return generatorHousingKit(options); }
export function pushButtonKit(options: Omit<KitOptions,"geometry"|"variants"> & { radius:number;height:number }): KitPart { const profile:readonly (readonly [number,number])[]=[[0,-options.height/2],[options.radius,-options.height/2],[options.radius,0],[options.radius*.78,options.height/2],[0,options.height/2]];return kitPart({...options,geometry:"cylinder",variants:variants({kind:"lathe",profile,radialSegments:36},{kind:"lathe",profile,radialSegments:24},{kind:"lathe",profile,radialSegments:12},options.label)}); }
export function leverCabinetKit(options: Omit<KitOptions,"geometry"|"variants"> & { width:number;height:number;depth:number;levers:number }): KitPart[] { const cabinet=structuralSupportKit(options);const levers=Array.from({length:options.levers},(_,i)=>structuralSupportKit({...options,id:`${options.id}-lever-${i+1}`,label:`${options.label} lever ${i+1}`,transform:transformAt(options.transform,[-options.width*.35+i*options.width*.7/Math.max(1,options.levers-1),options.height*.2,options.depth*.55],[0,0,-.35],[.08,options.height*.5,.08]),width:.15,height:1,depth:.15}));return[cabinet,...levers]; }
export function latticeTowerKit(options: Omit<KitOptions,"geometry"|"variants"> & { width:number;height:number;depth:number }): KitPart { const {width:w,height:h,depth:d}=options;const transforms:{position:[number,number,number];rotation:[number,number,number];scale:[number,number,number]}[]=[];for(const x of [-.5,.5])transforms.push({position:[x*w,0,0],rotation:[0,0,0],scale:[1,h,1]});for(let i=0;i<4;i++){const y=-h*.35+i*h*.23;transforms.push({position:[0,y,0],rotation:[0,0,i%2?-.55:.55],scale:[w*.7,1,d*.7]});}const bar:ParametricDescriptor={kind:"extrude",contour:[[-.035,-.5],[.035,-.5],[.035,.5],[-.035,.5]],depth:.05};const scatter:ParametricDescriptor={kind:"scatter",seed:5,prototype:bar,transforms};return kitPart({...options,geometry:"box",variants:variants(scatter,scatter,scatter,options.label)}); }
