export type PhaseOneCoverage = "full" | "partial";

export type PhaseOneTarget = {
  gradeLevel: number;
  subjectCode: string;
  coverage: PhaseOneCoverage;
};

export const PHASE_ONE_TARGETS: PhaseOneTarget[] = [
  ...[
    "MATH",
    "LITERACY",
    "SCIENCE",
    "SOCIAL_STUDIES",
    "CIVICS",
    "DIGITAL_LITERACY",
    "FINANCIAL_LITERACY",
    "CAREER_EXPLORATION",
    "COMMUNICATION_SKILLS",
    "PROBLEM_SOLVING",
    "CREATIVITY_INNOVATION",
    "AGRICULTURE",
    "ENVIRONMENTAL_STUDIES",
  ].map((subjectCode) => ({ gradeLevel: 5, subjectCode, coverage: "full" as const })),
  ...[
    "MATH",
    "ENGLISH",
    "SCIENCE",
    "SOCIAL_STUDIES",
    "CIVICS",
    "COMPUTER_SCIENCE",
    "ENGINEERING_FOUNDATIONS",
    "AI_LITERACY",
    "DATA_LITERACY",
    "BUSINESS_ENTREPRENEURSHIP",
    "FINANCIAL_LITERACY",
    "CAREER_EXPLORATION",
    "DIGITAL_LITERACY",
    "COMMUNICATION_SKILLS",
    "PROBLEM_SOLVING",
    "CREATIVITY_INNOVATION",
    "AGRICULTURE",
    "ENVIRONMENTAL_STUDIES",
    "ENERGY_INFRASTRUCTURE",
  ].map((subjectCode) => ({ gradeLevel: 7, subjectCode, coverage: "full" as const })),
  ...[
    "MATH",
    "LITERACY",
    "SCIENCE",
    "SOCIAL_STUDIES",
  ].map((subjectCode) => ({ gradeLevel: 3, subjectCode, coverage: "partial" as const })),
  ...[
    "ENGLISH",
    "SCIENCE",
    "CIVICS",
    "COMPUTER_SCIENCE",
    "BUSINESS_ENTREPRENEURSHIP",
    "DATA_LITERACY",
  ].map((subjectCode) => ({ gradeLevel: 10, subjectCode, coverage: "partial" as const })),
];

export const SUBJECT_UNIT_THEMES: Record<string, string[]> = {
  MATH: [
    "Number Sense and Place Value",
    "Addition and Subtraction Reasoning",
    "Multiplication and Division Strategies",
    "Fractions and Equivalence",
    "Decimals and Percentages",
    "Ratio and Proportion",
    "Measurement and Estimation",
    "Geometry and Spatial Reasoning",
    "Data Representation and Interpretation",
    "Algebraic Patterns and Expressions",
    "Problem Solving in Context",
    "Exam Strategy and Mathematical Communication",
  ],
  ENGLISH: [
    "Reading Fluency and Comprehension",
    "Vocabulary in Context",
    "Grammar for Clear Communication",
    "Sentence and Paragraph Craft",
    "Narrative Writing",
    "Informational Reading",
    "Speaking and Listening",
    "Argument and Evidence",
    "Literary Response",
    "Research and Note-Making",
    "Revision and Editing",
    "WAEC-Style Reading and Writing",
  ],
  LITERACY: [
    "Listening, Speaking, and Story Language",
    "Reading Readiness and Vocabulary",
    "Story Sequencing and Retelling",
    "Main Idea and Key Details",
    "Questioning for Understanding",
    "Sentence Building and Meaning",
    "Paragraph Thinking",
    "Inference and Clues",
    "Summarizing and Retelling",
    "Informational Reading",
    "Writing for Understanding",
    "Reading Confidence and Reflection",
  ],
  SCIENCE: [
    "Scientific Observation and Investigation",
    "Living Things and Their Needs",
    "Plant Systems and Food Making",
    "Animal Systems and Habitats",
    "Matter and Materials",
    "Forces and Motion",
    "Energy, Light, and Sound",
    "Earth, Weather, and Water",
    "Human Body and Health",
    "Ecosystems and Environment",
    "Data in Science",
    "Scientific Problem Solving",
  ],
  SOCIAL_STUDIES: [
    "Family, Community, and Identity",
    "Maps, Places, and Direction",
    "Liberia and Local Communities",
    "Culture, Heritage, and Traditions",
    "Rules, Roles, and Responsibilities",
    "Trade, Markets, and Work",
    "History Through Sources and Stories",
    "Citizenship in Action",
    "Environment and Community Life",
    "Leadership and Participation",
    "National Systems and Services",
    "Decision Making for Community Good",
  ],
  CIVICS: [
    "Rules, Rights, and Responsibilities",
    "Citizenship and Participation",
    "Community Leadership and Service",
    "Institutions and Public Trust",
    "Conflict Resolution and Dialogue",
    "Justice, Fairness, and Law",
    "Democracy and Representation",
    "Ethics in Public Life",
    "National Unity and Identity",
    "Civic Problem Solving",
    "Media, Information, and Citizenship",
    "Civic Readiness and Action",
  ],
  DIGITAL_LITERACY: [
    "Digital Safety and Responsible Use",
    "Typing, Input, and Device Basics",
    "Using Digital Tools for Learning",
    "File Skills and Information Storage",
    "Searching and Evaluating Information",
    "Digital Communication",
    "Productivity and Organization",
    "Visual and Audio Creation",
    "Digital Collaboration",
    "Problem Solving with Devices",
    "Digital Citizenship",
    "Independent Digital Learning",
  ],
  FINANCIAL_LITERACY: [
    "Money, Value, and Choices",
    "Saving and Planning",
    "Budgeting for Needs and Wants",
    "Price Comparison and Decision Making",
    "Income, Work, and Enterprise",
    "Records and Personal Finance",
    "Borrowing and Risk",
    "Household Financial Reasoning",
    "Markets and Trade",
    "Goal Setting with Money",
    "Ethics in Financial Choices",
    "Financial Communication and Reflection",
  ],
  CAREER_EXPLORATION: [
    "Work Habits and Responsibility",
    "Knowing My Strengths",
    "Jobs in School and Community",
    "Careers in Liberia",
    "Learning Pathways and Goals",
    "Communication for Work",
    "Problem Solving at Work",
    "Team Roles and Collaboration",
    "Digital Skills for Work",
    "Entrepreneurial Thinking",
    "Career Decision Making",
    "Pathways, Planning, and Reflection",
  ],
  COMMUNICATION_SKILLS: [
    "Listening for Understanding",
    "Speaking Clearly and Confidently",
    "Questioning and Clarifying",
    "Conversation and Collaboration",
    "Presentations and Public Speaking",
    "Writing to Inform",
    "Writing to Persuade",
    "Feedback and Revision",
    "Communication in Teams",
    "Professional and Civic Communication",
    "Storytelling and Audience Awareness",
    "Communication for Leadership",
  ],
  PROBLEM_SOLVING: [
    "Understanding the Problem",
    "Planning a Strategy",
    "Testing and Checking Solutions",
    "Reasoning with Evidence",
    "Comparing Solution Paths",
    "Patterns and Decision Making",
    "Applied Problem Solving",
    "Collaborative Problem Solving",
    "Creative Constraints and Tradeoffs",
    "Data-Based Decisions",
    "Reflection and Improvement",
    "Independent Challenge Solving",
  ],
  CREATIVITY_INNOVATION: [
    "Ideas, Curiosity, and Exploration",
    "Observation and Design Thinking",
    "Creative Expression and Choice",
    "Prototyping and Improvement",
    "Visual Design and Communication",
    "Innovation for Community Needs",
    "Creative Problem Solving",
    "Story, Media, and Message",
    "Collaboration in Creation",
    "Feedback and Revision",
    "Original Products and Presentation",
    "Innovation Reflection and Impact",
  ],
  AGRICULTURE: [
    "Agriculture and Community Life",
    "Soil, Water, and Growing Conditions",
    "Seeds, Germination, and Plant Care",
    "Crop Growth and Management",
    "Pests, Disease, and Protection",
    "Food Systems and Nutrition",
    "Tools, Safety, and Farm Work",
    "Records, Measurement, and Yield",
    "Agribusiness and Markets",
    "Sustainability in Agriculture",
    "Agriculture and Technology",
    "Leadership in Local Food Systems",
  ],
  ENVIRONMENTAL_STUDIES: [
    "Local Environment and Stewardship",
    "Water, Sanitation, and Health",
    "Waste and Recycling",
    "Weather, Climate, and Daily Life",
    "Habitats and Biodiversity",
    "Soil and Land Use",
    "Energy Choices and Conservation",
    "Community Risk and Resilience",
    "Environmental Data and Observation",
    "Human Impact and Responsibility",
    "Sustainable Solutions",
    "Community Action for the Environment",
  ],
  COMPUTER_SCIENCE: [
    "Computers and Digital Systems",
    "Algorithms and Logical Thinking",
    "Programming Sequences",
    "Conditionals and Decisions",
    "Loops and Repetition",
    "Debugging and Improvement",
    "Data and Representation",
    "Networks and the Internet",
    "User Design and Interfaces",
    "Automation and Problem Solving",
    "Ethics in Computing",
    "Computing Projects and Reflection",
  ],
  ENGINEERING_FOUNDATIONS: [
    "Engineering Design Process",
    "Forces, Structures, and Stability",
    "Materials and Properties",
    "Measurement for Building",
    "Energy in Design",
    "Systems and Components",
    "Prototyping and Testing",
    "Failure Analysis and Improvement",
    "Engineering for Community Needs",
    "Design Constraints and Tradeoffs",
    "Documentation and Presentation",
    "Engineering Projects and Reflection",
  ],
  AI_LITERACY: [
    "What AI Is and Is Not",
    "Data, Patterns, and Predictions",
    "Prompts and Human Guidance",
    "Bias, Fairness, and Risk",
    "AI in Learning and Work",
    "Checking AI Outputs",
    "Human Judgment and Oversight",
    "AI for Problem Solving",
    "Responsible Use in Community Life",
    "Creativity with AI Tools",
    "Privacy and Safety in AI Use",
    "AI Reflection and Future Readiness",
  ],
  DATA_LITERACY: [
    "Collecting Useful Data",
    "Organizing Data Clearly",
    "Tables, Charts, and Graphs",
    "Comparing Quantities with Data",
    "Patterns, Trends, and Outliers",
    "Interpreting Real-World Data",
    "Questioning Data Quality",
    "Making Claims from Evidence",
    "Data for Community Decisions",
    "Digital Data Tools",
    "Data Communication",
    "Data Reflection and Ethics",
  ],
  BUSINESS_ENTREPRENEURSHIP: [
    "Opportunity and Problem Finding",
    "Customers and Community Needs",
    "Products, Services, and Value",
    "Simple Market Research",
    "Pricing and Cost Thinking",
    "Budgeting for Small Enterprise",
    "Planning, Roles, and Operations",
    "Communication and Selling",
    "Ethics and Trust in Business",
    "Records and Performance",
    "Growth, Risk, and Adaptation",
    "Pitching and Enterprise Reflection",
  ],
  ENERGY_INFRASTRUCTURE: [
    "Infrastructure in Daily Life",
    "Water, Power, and Access",
    "Roads, Buildings, and Safety",
    "Energy Sources and Tradeoffs",
    "Maintenance and Reliability",
    "Infrastructure and Community Health",
    "Measurement in Infrastructure Systems",
    "Data for Infrastructure Decisions",
    "Resilience and Repair",
    "Innovation in Energy Use",
    "Workforce Roles in Infrastructure",
    "Planning for Sustainable Systems",
  ],
};

