/**
 * Builds the committed Grade 4 Math Curriculum V2 review package (curriculum/review/g4-math-v2/)
 * from the proof candidates. Deterministic: tests regenerate it in memory and fail when the
 * committed files are stale, so the package always describes exactly what the code produces.
 */
import { GRADE4_MATH_DRAFT_LESSONS } from "@/lib/curriculum/authority/grade4Math";
import { assembleCurriculumLessonV2 } from "./assemble";
import { artifactHash, G4_PROOF_GENERATED_AT, G4_PROOF_SAMPLE, g4ProofContext, runG4Proof } from "./g4Proof";
import { migrateDraftLesson } from "./migrate";
import { reviewPackageMarkdown } from "./reviewPackage";

export const G4_PROOF_PACKAGE_DIR = "curriculum/review/g4-math-v2";
/** The one legacy draft migrated to prove the adapter (not mass conversion). */
export const G4_MIGRATION_DEMO_CONTENT_ID = "ll-g4-math-read-write-numbers-to-100000-2026.1";

export function buildG4ProofPackageFiles(): Map<string, string> {
  const files = new Map<string, string>();
  const rows: string[] = [];
  for (const entry of G4_PROOF_SAMPLE) {
    const outcome = runG4Proof(entry.file, entry.objectiveId);
    const name = entry.file.replace(/\.json$/, "");
    if (outcome.status === "REJECTED") {
      rows.push(`| ${entry.strand} | \`${entry.objectiveId}\` | REJECTED | ${outcome.errors.join(", ")} | — |`);
      continue;
    }
    const hash = artifactHash(outcome.lesson);
    files.set(`${name}.md`, reviewPackageMarkdown({ lesson: outcome.lesson, status: outcome.status, deliverability: outcome.deliverability, artifactHash: hash }));
    files.set(`artifacts/${name}.json`, `${JSON.stringify(outcome.lesson, null, 2)}\n`);
    const blocking = outcome.lesson.reviewGaps.filter((gap) => gap.severity === "BLOCKING").map((gap) => gap.code);
    rows.push(`| ${entry.strand} | \`${entry.objectiveId}\` | ${outcome.status} | ${outcome.lesson.scenes.length} scenes: ${[...new Set(outcome.lesson.scenes.map((scene) => scene.type))].join(", ")} | ${blocking.length ? blocking.join(", ") : "none"} | [review](${name}.md) |`);
  }

  // Migration demo: one legacy DRAFT_UNREVIEWED lesson through the bounded adapter.
  const draft = GRADE4_MATH_DRAFT_LESSONS.find((lesson) => lesson.contentId === G4_MIGRATION_DEMO_CONTENT_ID)!;
  const context = g4ProofContext(draft.moeObjectiveId);
  const { candidate, migration } = migrateDraftLesson(draft, context);
  const migrated = assembleCurriculumLessonV2({ candidate, context, generation: { origin: "MIGRATED_LEGACY", promptKey: null, promptVersion: null, promptHash: null, model: null, generatedAt: G4_PROOF_GENERATED_AT, migration } });
  if (migrated.status !== "REJECTED") {
    files.set("migration-demo.md", reviewPackageMarkdown({ lesson: migrated.lesson, status: migrated.status, deliverability: migrated.deliverability, artifactHash: artifactHash(migrated.lesson) }));
  } else {
    files.set("migration-demo.md", `# Migration demo: ${draft.contentId}\n\nREJECTED: ${migrated.errors.join(", ")}\n`);
  }

  files.set("README.md", [
    "# Grade 4 Math — Curriculum V2 review package (vertical proof)",
    "",
    "Generated by `scripts/build-curriculum-v2-g4-proof.ts` from `curriculum/v2/g4-math/candidates/`. Do not edit by hand: edit a candidate and regenerate (`npx tsx scripts/build-curriculum-v2-g4-proof.ts`). A test fails if these files are stale.",
    "",
    "Every artifact is a **DRAFT** that requires exact-revision **HUMAN_REVIEW**. None is approved, published or MOE-approved. Candidates were written offline in the generator's output format (`AUTHORED_FIXTURE`); no live model call produced them. Each passed the same strict parser, pinned authoring context (structured MOE source → template cell → ontology release `lr-moe-g4-math-fractions-2026.1`), validator, lab resolution and deliverability checks as generated output.",
    "",
    "| Strand | MOE objective | Status | Structure | Blocking gaps | Package |",
    "| --- | --- | --- | --- | --- | --- |",
    ...rows,
    "",
    `Migration demo: [${draft.contentId}](migration-demo.md) (\`${migrated.status}\`) shows the bounded legacy adapter with source hash, section map and omissions.`,
    "",
    "Statuses: `READY_FOR_HUMAN_REVIEW` (no blocking gap; a qualified reviewer may still revise or reject) and `REVIEW_BLOCKED` (a blocking gap, such as missing governed assessment items or a required media asset, must be closed first). Review decisions are recorded through governed curriculum review against the exact artifact hash, never in this folder.",
    "",
  ].join("\n"));
  return files;
}
