import { z } from "zod";

export const PseudoLabSchema = z.object({
  id: z.string().min(1),
  sourceLessonId: z.string().min(1),
  subject: z.string().min(1),
  gradeLevel: z.number().int().min(1).max(12),
  unitTitle: z.string().min(1),
  lessonTitle: z.string().min(1),
  lessonObjective: z.string().min(5),
  title: z.string().min(3),
  objective: z.string().min(5),
  labType: z.enum(["classroom", "home", "simulation", "3d_future"]),
  difficulty: z.enum(["intro", "standard", "advanced"]),
  priority: z.enum(["core", "supporting", "optional"]),
  resourceLevel: z.enum(["low", "medium", "high"]),
  offlineCapable: z.boolean(),
  deviceRequired: z.enum(["none", "shared", "student"]),
  electricityRequired: z.boolean(),
  riskLevel: z.enum(["low", "medium", "high"]),
  requiredMaterials: z.array(z.string().min(1)).min(1),
  optionalMaterials: z.array(z.string().min(1)).default([]),
  setupTimeMinutes: z.number().int().min(0).max(30),
  runTimeMinutes: z.number().int().min(5).max(60),
  cleanupTimeMinutes: z.number().int().min(0).max(20),
  prepComplexity: z.enum(["low", "medium", "high"]),
  safetyNotes: z.string().min(5),
  setupInstructions: z.array(z.string().min(10)).min(1),
  procedureSteps: z.array(z.string().min(10)).min(2),
  expectedObservation: z.string().min(10),
  explanation: z.string().min(10),
  reflectionQuestions: z.array(z.string().min(5)).min(2),
  extensionIdea: z.string().min(10),
  guardianHomeVariant: z.string().min(10).nullable(),
  fallbackMode: z.string().min(10),
  fallbackIfNoMaterials: z.string().min(10),
  expectedCompletionTimeMinutes: z.number().int().min(5).max(60),
  expectedSuccessRate: z.number().min(0).max(1),
  commonConfusionSignals: z.array(z.string().min(3)).min(1),
  conceptTags: z.array(z.string().min(1)).min(1),
  simulationType: z.enum(["none", "slider", "toggle", "step_based", "sequence_ordering", "simple_visual_interactive"]),
  threeDLabReady: z.boolean(),
  renderStatus: z.enum(["pending", "ready", "failed"]),
  approved: z.boolean(),
});

export const SimulationDefinitionSchema = z.object({
  id: z.string().min(1),
  sourceLessonId: z.string().min(1),
  subject: z.string().min(1),
  gradeLevel: z.number().int().min(1).max(12),
  unitTitle: z.string().min(1),
  lessonTitle: z.string().min(1),
  lessonObjective: z.string().min(5),
  title: z.string().min(3),
  simulationType: z.enum(["slider", "toggle", "step_based", "sequence_ordering", "simple_visual_interactive"]),
  rendererKey: z.string().min(1),
  fallbackRendererKey: z.string().min(1),
  inputs: z.array(
    z.object({
      key: z.string().min(1),
      label: z.string().min(1),
      type: z.enum(["range", "toggle", "step", "choice", "order"]),
      min: z.number().optional(),
      max: z.number().optional(),
      step: z.number().optional(),
      options: z.array(z.string()).optional(),
      defaultValue: z.union([z.number(), z.string(), z.boolean(), z.array(z.string())]).optional(),
    })
  ).min(1),
  outputs: z.array(
    z.object({
      key: z.string().min(1),
      label: z.string().min(1),
      description: z.string().min(3),
    })
  ).min(1),
  interactionModel: z.string().min(10),
  uiConfig: z.object({
    compact: z.boolean(),
    showTeacherNotes: z.boolean(),
    showGuardianMode: z.boolean(),
    accentColor: z.string().min(3),
  }),
  objective: z.string().min(5),
  explanation: z.string().min(10),
  teacherGuide: z.string().min(10),
  guardianGuide: z.string().min(10).nullable(),
  fallbackStaticVisual: z.string().min(10),
  attemptTrackingEnabled: z.boolean(),
  supportsStateSave: z.boolean(),
  stateSchema: z.record(z.string(), z.string()).optional(),
  progressTrackingEnabled: z.boolean(),
  renderStatus: z.enum(["pending", "ready", "failed"]),
  approved: z.boolean(),
});

export const ThreeDLabDefinitionSchema = z.object({
  id: z.string().min(1),
  sourceLessonId: z.string().min(1),
  subject: z.string().min(1),
  gradeLevel: z.number().int().min(1).max(12),
  unitTitle: z.string().min(1),
  lessonTitle: z.string().min(1),
  title: z.string().min(3),
  objective: z.string().min(5),
  sceneType: z.string().min(3),
  requiredObjects: z.array(z.string().min(1)).min(1),
  interactions: z.array(z.string().min(5)).min(1),
  learningChecks: z.array(z.string().min(5)).min(1),
  teacherGuide: z.string().min(10),
  fallbackMode: z.string().min(10),
  status: z.enum(["planned", "pseudo_lab", "simulation_ready", "three_d_ready"]),
});

export type PseudoLab = z.infer<typeof PseudoLabSchema>;
export type SimulationDefinition = z.infer<typeof SimulationDefinitionSchema>;
export type ThreeDLabDefinition = z.infer<typeof ThreeDLabDefinitionSchema>;
