import { describe, expect, it } from "vitest";
import { EVENT_REGISTRY, GOVERNED_EVENT_SCHEMA_VERSION, METRIC_REGISTRY, calculateMetric, ingestGovernedEvents, validateGovernedEvent, type GovernedEvent } from "@/lib/measurement/governedMeasurement";

const base = (name: string, metadata: Record<string, unknown> = {}, overrides: Partial<GovernedEvent> = {}): GovernedEvent => ({ eventId: `event-${name}-${Math.random()}`, name, schemaVersion: GOVERNED_EVENT_SCHEMA_VERSION, occurredAt: "2026-08-10T12:00:00.000Z", schoolId: "school-a", actorType: "learner", actorId: "learner-a", syntheticSource: "production", metadata, ...overrides });
const window = { start: "2026-08-01T00:00:00.000Z", end: "2026-08-31T23:59:59.999Z" };

describe("P7-A governed event contract", () => {
  it("has one complete versioned registry for all required families", () => { expect(new Set(EVENT_REGISTRY.map((e) => e.family))).toEqual(new Set(METRIC_REGISTRY.map((m) => m.id))); expect(METRIC_REGISTRY).toHaveLength(9); for (const metric of METRIC_REGISTRY) { expect(metric.owner).toBeTruthy(); expect(metric.window).toBeTruthy(); expect(metric.denominator).toBeTruthy(); expect(metric.missingData).toBeTruthy(); } });
  it("quarantines unknown, unsupported, malformed, and privacy-unsafe metadata visibly", () => { expect(validateGovernedEvent(base("unknown.event"))).toMatchObject({ ok: false, reason: "unknown_event_name" }); expect(validateGovernedEvent(base("governed.learning.activity", { activeSeconds: 1 }, { schemaVersion: 99 }))).toMatchObject({ ok: false, reason: "unsupported_schema_version" }); expect(validateGovernedEvent(base("governed.learning.activity", {}))).toMatchObject({ ok: false, reason: "missing_required_metadata:activeSeconds" }); expect(validateGovernedEvent(base("governed.learning.activity", { activeSeconds: "invalid" }))).toMatchObject({ ok: false, reason: "invalid_metadata:activeSeconds" }); expect(validateGovernedEvent(base("governed.tutor.feedback", { helpful: true, response: "private" }))).toMatchObject({ ok: false, reason: "unregistered_metadata:response" }); });
  it("scopes replay identities to tenant and event name", () => { const e = base("governed.learning.activity", { activeSeconds: 60 }, { operationId: "offline-op-1" }); const result = ingestGovernedEvents([e, { ...e, eventId: "server-replay" }, { ...e, name: "governed.retention.learning_day", metadata: {} }, { ...e, schoolId: "school-b" }]); expect(result.accepted).toHaveLength(3); expect(result.duplicates).toBe(1); });
  it("enforces validation and deduplication in the calculator", () => { const valid = base("governed.learning.activity", { activeSeconds: 60 }, { operationId: "one" }); const result = calculateMetric("learning_dosage", [valid, { ...valid, eventId: "replay" }, base("governed.learning.activity", { activeSeconds: "bad" })], "school-a", window); expect(result.numerator).toBe(60); expect(result.duplicateEvents).toBe(1); expect(result.quarantinedEvents).toBe(1); });
  it("uses observable retention windows, eligible teacher populations, matched workflows, and required safety interactions", () => { const result = calculateMetric("retention", [base("governed.retention.cohort_entered", {}, { occurredAt: "2026-08-28T00:00:00.000Z" }), base("governed.retention.learning_day", {}, { occurredAt: "2026-08-27T00:00:00.000Z" })], "school-a", window); expect(result.denominator).toBe(0); expect(result.missingDataEvents).toBe(1); const adoption = calculateMetric("teacher_adoption", [base("governed.teacher.eligible", {}, { actorType: "teacher", actorId: "t1" }), base("governed.teacher.eligible", {}, { actorType: "teacher", actorId: "t2" }), base("governed.teacher.meaningful_action", { action: "assignment" }, { actorType: "teacher", actorId: "t1" })], "school-a", window); expect(adoption).toMatchObject({ numerator: 1, denominator: 2, value: 0.5 }); const workflow = calculateMetric("workflow_completion", [base("governed.workflow.started", { workflow: "submit", workflowId: "w" }, { occurredAt: "2026-08-10T12:00:00.000Z" }), base("governed.workflow.completed", { workflow: "submit", workflowId: "w" }, { occurredAt: "2026-08-11T13:00:01.000Z" })], "school-a", window); expect(workflow).toMatchObject({ numerator: 0, denominator: 1 }); const safety = calculateMetric("safety_decisions", [base("governed.safety.required", { interactionId: "one" }, { actorType: "system" }), base("governed.safety.required", { interactionId: "two" }, { actorType: "system" }), base("governed.safety.decision", { interactionId: "one", decision: "allowed", classifierVersion: "c1" }, { actorType: "system" })], "school-a", window); expect(safety).toMatchObject({ numerator: 1, denominator: 2, value: 0.5 }); });
  it("preserves tenant isolation, event time, and excludes synthetic events", () => { const events = [base("governed.learning.activity", { activeSeconds: 60 }), base("governed.learning.activity", { activeSeconds: 999 }, { syntheticSource: "fixture" }), base("governed.learning.activity", { activeSeconds: 999 }, { schoolId: "school-b" }), base("governed.learning.activity", { activeSeconds: 30 }, { occurredAt: "2026-07-31T23:59:59.000Z" })]; const result = calculateMetric("learning_dosage", events, "school-a", window); expect(result.numerator).toBe(60); expect(result.excludedSyntheticEvents).toBe(1); });
});

describe("P7-A golden metric fixtures", () => {
  const cases = [
    ["learning_dosage", "governed.learning.activity", { activeSeconds: 60 }, { activeSeconds: 0 }],
    ["retention", "governed.retention.cohort_entered", {}, {}],
    ["mastery_movement", "governed.mastery.snapshot", { mastery: 0.2, assessmentVersion: "v1", strandId: "s1" }, { mastery: 0.2 }],
    ["teacher_adoption", "governed.teacher.meaningful_action", { action: "assignment_created" }, {}],
    ["workflow_completion", "governed.workflow.started", { workflow: "submission", workflowId: "w1" }, {}],
    ["tutor_helpfulness", "governed.tutor.feedback", { helpful: true }, {}],
    ["ai_grounding", "governed.ai.grounding_evaluated", { grounded: true, evaluatorVersion: "e1", approvedContextAvailable: true }, { grounded: true }],
    ["hallucination", "governed.ai.hallucination_evaluated", { unsupportedClaim: true, evaluatorVersion: "e1", category: "unsupported_curriculum_claim" }, { unsupportedClaim: true }],
    ["safety_decisions", "governed.safety.decision", { decision: "blocked", classifierVersion: "c1" }, {}],
  ] as const;
  for (const [metric, event, metadata, incomplete] of cases) {
    it(`${metric}: positive, negative/ineligible, missing, and synthetic cases are deterministic`, () => {
      const actorType = metric === "teacher_adoption" ? "teacher" : metric === "safety_decisions" || metric === "ai_grounding" || metric === "hallucination" ? "reviewer" : "learner";
      const positive = base(event, metadata, { actorType });
      const negative = metric === "retention" ? base("governed.retention.learning_day", {}, { actorId: "other" }) : metric === "mastery_movement" ? base(event, { ...metadata, mastery: 0.1 }, { actorType, eventId: "later", occurredAt: "2026-08-11T12:00:00.000Z" }) : metric === "workflow_completion" ? base("governed.workflow.completed", { workflow: "submission", workflowId: "w1" }, { actorType }) : base(event, incomplete, { actorType, eventId: "incomplete" });
      const synthetic = base(event, metric === "safety_decisions" ? { ...metadata, interactionId: "synthetic-i" } : metadata, { actorType, syntheticSource: "fixture", eventId: "synthetic" });
      const events = metric === "retention" ? [positive, base("governed.retention.learning_day", {}, { actorId: "learner-a", occurredAt: "2026-08-11T12:00:00.000Z" }), negative, synthetic] : metric === "mastery_movement" ? [positive, base(event, { ...metadata, mastery: 0.8 }, { actorType, eventId: "later", occurredAt: "2026-08-11T12:00:00.000Z" }), synthetic] : metric === "teacher_adoption" ? [base("governed.teacher.eligible", {}, { actorType: "teacher" }), positive, negative, synthetic] : metric === "safety_decisions" ? [base("governed.safety.required", { interactionId: "i1" }, { actorType: "system" }), base(event, { ...metadata, interactionId: "i1" }, { actorType }), negative, synthetic] : [positive, negative, synthetic];
      const result = calculateMetric(metric, events, "school-a", window);
      expect(result.metricVersion).toBe(1); expect(result.excludedSyntheticEvents).toBe(1); expect(result.denominator).toBeGreaterThanOrEqual(1); expect(result.numerator).toBeGreaterThanOrEqual(0);
    });
  }
});
